/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.petClinic;

import Business.Enterprise.Enterprise;
import Business.PetClinicOrganization.FrontDeskOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.HealthCareCheckRequest;
import Business.WorkQueue.InsuranceClaimRequest;
import Business.WorkQueue.WorkRequest;
import UI.admin.MainJFrame;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jingyangwang
 */
public class FrontDeskManagementJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount account;
    private FrontDeskOrganization frontDeskOrg;
    private Enterprise enterprise;
    private MainJFrame mainJFrame;
    
    /**
     * Creates new form FrontDeskManagementJPanel
     */
    public FrontDeskManagementJPanel(JPanel userProcessContainer, UserAccount account, FrontDeskOrganization frontDeskOrg, Enterprise enterprise) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.frontDeskOrg = frontDeskOrg;
        this.enterprise = enterprise;
        

        populateTable();
        populateClaimTable();
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFrontDesk = new javax.swing.JTable();
        btnViewDetails = new javax.swing.JButton();
        btnViewMedicalStatus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblClaims = new javax.swing.JTable();

        title.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        title.setText("Welcome Front Desk");

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        tblFrontDesk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Patient ID", "Message", "Sender", "Symptom", "Assigned Doctor", "Health Check Status "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblFrontDesk);

        btnViewDetails.setText("View Details");
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });

        btnViewMedicalStatus.setText("View Medical Status");
        btnViewMedicalStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMedicalStatusActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel1.setText("Tracking Insurance Claim Request ");

        tblClaims.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Claim ID", "Patient ID", "Claim Amount", "Decision", "Claim Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblClaims);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 956, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnViewMedicalStatus, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                        .addComponent(btnViewDetails, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 972, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title)
                    .addComponent(btnLogout))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnViewDetails)
                .addGap(18, 18, 18)
                .addComponent(btnViewMedicalStatus)
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblFrontDesk.getSelectedRow();
        //check if its selected
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row to view details.");
            return;
        }

        //select the whole request object
        HealthCareCheckRequest request = (HealthCareCheckRequest) tblFrontDesk.getValueAt(selectedRow, 0);

        //connect to next jpanel
        ViewDetailsJPanel panel = new ViewDetailsJPanel(userProcessContainer, request,enterprise);
        userProcessContainer.add("ViewDetailsJPanel", panel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewDetailsActionPerformed

    private void btnViewMedicalStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMedicalStatusActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblFrontDesk.getSelectedRow();
        //check if its selected
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row first.");
            return;
        }

        HealthCareCheckRequest request = (HealthCareCheckRequest) tblFrontDesk.getValueAt(selectedRow, 0);

        ViewMedicalStatusJPanel panel = new ViewMedicalStatusJPanel(userProcessContainer, request, account, enterprise);

        userProcessContainer.add("ViewMedicalStatusJPanel", panel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewMedicalStatusActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        java.awt.Component comp = this;

        // 向上遍历组件树，直到找到 MainJFrame
        while (comp != null && !(comp instanceof UI.admin.MainJFrame)) {
            comp = comp.getParent();
        }

        if (comp instanceof UI.admin.MainJFrame) {
            // ⭐ 关键修正：调用新的公共代理方法
            ((UI.admin.MainJFrame) comp).triggerLogout(); 
        } else {
            // 找不到 MainJFrame，执行后备方案
            if (userProcessContainer != null) {
                userProcessContainer.removeAll();
                userProcessContainer.revalidate();
                userProcessContainer.repaint();
        }
    }
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JButton btnViewMedicalStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblClaims;
    private javax.swing.JTable tblFrontDesk;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

    public void populateTable() {
        
        //cltblHealthCheckRequeste
        DefaultTableModel model = (DefaultTableModel) tblFrontDesk.getModel();
        model.setRowCount(0);
        
        //get the work queue from front desk organization and loop for each work request
        for (WorkRequest request : frontDeskOrg.getWorkQueue().getWorkRequestList()) {
            //if the work request belongs to health care check request populate table
            if (request instanceof HealthCareCheckRequest req) {

                Object[] row = new Object[6];
                row[0] = req;
                row[1] = req.getMessage();
                row[2] = req.getSender() == null ? "Unknown" : req.getSender().getUsername();
                row[3] = req.getSymptom();
                row[4] = req.getAssignedDoctor() == null ? "Not Assigned" : req.getAssignedDoctor();
                row[5] = req.getStatus();  

                model.addRow(row);
            }
        }
    }

    private void populateClaimTable() {
        DefaultTableModel model = (DefaultTableModel) tblClaims.getModel();
        model.setRowCount(0);

        for (WorkRequest wr : frontDeskOrg.getWorkQueue().getWorkRequestList()) {
            if (wr instanceof InsuranceClaimRequest claim) {

                Object[] row = new Object[5];

                row[0] = claim.getClaimId();       
                row[1] = claim.getHealthRequest() == null ? "Unknown" : claim.getHealthRequest().getPatientId();  
                row[2] = claim.getClaimAmount();   
                row[3] = claim.getClaimDecision(); 
                row[4] = claim.getStatus();        

                model.addRow(row);
                }
            }
    }
}
