/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.petClinic;

import Business.PetClinicOrganization.FrontDeskOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.HealthCareCheckRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jingyangwang
 */
public class FrontDeskManagementJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount account;
    private FrontDeskOrganization frontDeskOrg;
    /**
     * Creates new form FrontDeskManagementJPanel
     */
    public FrontDeskManagementJPanel(JPanel userProcessContainer, UserAccount account, FrontDeskOrganization frontDeskOrg) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.frontDeskOrg = frontDeskOrg;

        populateTable();
        
        //以下是测试数据！！
        // test data
        HealthCareCheckRequest testReq = new HealthCareCheckRequest();
        testReq.setPatientId(1001);
        testReq.setMessage("Pet needs urgent health check");
        testReq.setSender(account);   // front desk自己假装 sender
        testReq.setSymptom("vomiting");
        testReq.setAssignedDoctor(null);
        testReq.setLabResult(null);
        testReq.setInsuranceClaimRequest(null);

        // 加到 front desk的 work queue
        frontDeskOrg.getWorkQueue().getWorkRequestList().add(testReq);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFrontDesk = new javax.swing.JTable();
        btnViewDetails = new javax.swing.JButton();
        btnViewMedicalStatus = new javax.swing.JButton();

        title.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        title.setText("Welcome Front Desk");

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        tblFrontDesk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Patient ID", "Message", "Sender", "Symptom", "Assigned Doctor", "Lab result", "Insurance Claim Request"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblFrontDesk);

        btnViewDetails.setText("View Details");
        btnViewDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailsActionPerformed(evt);
            }
        });

        btnViewMedicalStatus.setText("View Medical Status");
        btnViewMedicalStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMedicalStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 887, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnViewDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnViewMedicalStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(title)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title)
                    .addComponent(btnLogout))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(btnViewDetails)
                .addGap(31, 31, 31)
                .addComponent(btnViewMedicalStatus)
                .addContainerGap(103, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnViewDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailsActionPerformed
        //get selected row
        int selectedRow = tblFrontDesk.getSelectedRow();
        //selected row can not be null
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select to view details.");
            return;
        }

        //get information from jtable
        HealthCareCheckRequest request = (HealthCareCheckRequest) tblFrontDesk.getValueAt(selectedRow, 0);

        ViewDetailsJPanel panel = new ViewDetailsJPanel(userProcessContainer, request);
        userProcessContainer.add("ViewDetailsJPanel", panel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    
       
    }//GEN-LAST:event_btnViewDetailsActionPerformed

    private void btnViewMedicalStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMedicalStatusActionPerformed
        //get selected row
        int selectedRow = tblFrontDesk.getSelectedRow();

        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row first.");
            return;
        }
        //get information from jtable
        HealthCareCheckRequest request = (HealthCareCheckRequest) tblFrontDesk.getValueAt(selectedRow, 0);
        
        ViewMedicalStatusJPanel panel = new ViewMedicalStatusJPanel(userProcessContainer, request);
        userProcessContainer.add("ViewMedicalStatusJPanel", panel);

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnViewMedicalStatusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnViewDetails;
    private javax.swing.JButton btnViewMedicalStatus;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFrontDesk;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        
        //clear the table
        DefaultTableModel model = (DefaultTableModel) tblFrontDesk.getModel();
        model.setRowCount(0);
        
        //get the work queue from front desk organization and loop for each work request
        for (WorkRequest request : frontDeskOrg.getWorkQueue().getWorkRequestList()) {
            //if the work request belongs to health care check request populate table
            if (request instanceof HealthCareCheckRequest req) {

                Object[] row = new Object[7];
                
                row[0] = req;// 放request本体
                row[1] = req.getMessage();  
                row[2] = req.getSender() == null ? "Unknown" : req.getSender().getUsername();
                row[3] = req.getSymptom() == null ? "None" : req.getSymptom();
                row[4] = req.getAssignedDoctor() == null ? "Not Assigned" : req.getAssignedDoctor();
                row[5] = req.getLabResult() == null ? "Pending" : req.getLabResult();
                row[6] = req.getInsuranceClaimRequest() == null ? "Not Submitted" : req.getInsuranceClaimRequest();

                model.addRow(row);
            }
        }
    }
}
