/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.petClinic;


import Business.Enterprise.Enterprise;
import Business.Enterprise.PetInsuranceEnterprise;
import Business.Organization.Organization;
import Business.Pet.Pet;
import Business.PetClinicOrganization.FrontDeskOrganization;
import Business.PetInsuranceOrganization.InsuranceClaimOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.HealthCareCheckRequest;
import Business.WorkQueue.InsuranceClaimRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

import Business.Network.Network;
import Business.Enterprise.PetBoardingEnterprise;
import Business.PetBoardingOrganization.CustomerService;
import Business.Petsystem;

/**
 *
 * @author jingyangwang
 */
public class SubmitInsuranceClaimRequestJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private HealthCareCheckRequest Request;
    private UserAccount account;
    private PetInsuranceEnterprise insuranceEnterprise;
    private FrontDeskOrganization frontDeskOrg;
    private final java.util.Map<String, Double> treatmentPriceMap = new java.util.HashMap<>();
    
    /**
     * Creates new form SubmitInsuranceClaimRequestJPanel
     */
    public SubmitInsuranceClaimRequestJPanel(JPanel userProcessContainer, HealthCareCheckRequest Request,UserAccount account,
        PetInsuranceEnterprise insuranceEnterprise,FrontDeskOrganization frontDeskOrg) {
        
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.Request = Request;
        this.account = account;
        this.insuranceEnterprise = insuranceEnterprise;
        this.frontDeskOrg = frontDeskOrg;
        
        initTreatmentPrice();
        populateData();
        
        
        
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        fieldPetName = new javax.swing.JTextField();
        fieldSpieces = new javax.swing.JTextField();
        fieldAge = new javax.swing.JTextField();
        fieldWeight = new javax.swing.JTextField();
        fieldFoodAllergy = new javax.swing.JTextField();
        lblPetName = new javax.swing.JLabel();
        lblSpecies = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblWeight = new javax.swing.JLabel();
        lblFoodAllergy = new javax.swing.JLabel();
        lblPet = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblInsuranceCompany = new javax.swing.JLabel();
        lblPolicyID = new javax.swing.JLabel();
        lblCoverageLevel = new javax.swing.JLabel();
        lblExpirationDate = new javax.swing.JLabel();
        fieldInsuranceCompany = new javax.swing.JTextField();
        fieldPolicyID = new javax.swing.JTextField();
        fieldExpirationDate = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lblMedicalResult = new javax.swing.JLabel();
        lblLabTestResult = new javax.swing.JLabel();
        lblTreatmentNeeded = new javax.swing.JLabel();
        lblTreatmentCost = new javax.swing.JLabel();
        fieldLabTestResult = new javax.swing.JTextField();
        fieldTreatmentCost = new javax.swing.JTextField();
        comboTreatmentNeeded = new javax.swing.JComboBox<>();
        comboCoverageLevel = new javax.swing.JComboBox<>();
        btnSubmitInsuranceClaimRequest = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        jLabel1.setText(" Create Insurance Claim Request");

        btnBack.setText("<<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblPetName.setText("Pet Name");

        lblSpecies.setText("Species");

        lblAge.setText("Age");

        lblWeight.setText("Weight");

        lblFoodAllergy.setText("Food Allergy");

        lblPet.setText("Pet");

        jLabel2.setText("Pet Insurance");

        lblInsuranceCompany.setText("Insurance Company");

        lblPolicyID.setText("Policy ID");

        lblCoverageLevel.setText("Coverage Level");

        lblExpirationDate.setText("Expiration Date");

        lblMedicalResult.setText("Medical Result");

        lblLabTestResult.setText("Lab Test Result");

        lblTreatmentNeeded.setText("Treatment Needed");

        lblTreatmentCost.setText("Treatment Cost");

        comboTreatmentNeeded.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Medication Only ", "IV Fluids & Supportive Care ", "Diagnostic Imaging (X-ray / Ultrasound) ", "Surgery ", "Hospitalization " }));
        comboTreatmentNeeded.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTreatmentNeededActionPerformed(evt);
            }
        });

        comboCoverageLevel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Full Coverage 100%", "Partial Coverage 50%", " ", " " }));

        btnSubmitInsuranceClaimRequest.setText("Submit Insurance Claim Request");
        btnSubmitInsuranceClaimRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitInsuranceClaimRequestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addComponent(lblPet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(265, 265, 265))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(btnSubmitInsuranceClaimRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(75, 75, 75)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblPetName)
                                .addComponent(lblSpecies)
                                .addComponent(lblAge)
                                .addComponent(lblWeight)
                                .addComponent(lblFoodAllergy))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fieldFoodAllergy, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fieldSpieces, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldPetName, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(96, 96, 96)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblInsuranceCompany)
                                .addComponent(lblPolicyID)
                                .addComponent(lblCoverageLevel)
                                .addComponent(lblExpirationDate))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(fieldInsuranceCompany)
                                .addComponent(fieldPolicyID)
                                .addComponent(fieldExpirationDate)
                                .addComponent(comboCoverageLevel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(41, 41, 41)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 364, Short.MAX_VALUE)
                                            .addComponent(btnBack)
                                            .addGap(13, 13, 13))
                                        .addComponent(jSeparator1)
                                        .addComponent(jSeparator2)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(197, 197, 197)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblTreatmentNeeded)
                                        .addComponent(lblLabTestResult)
                                        .addComponent(lblTreatmentCost))
                                    .addGap(62, 62, 62)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(fieldLabTestResult)
                                        .addComponent(comboTreatmentNeeded, 0, 1, Short.MAX_VALUE)
                                        .addComponent(fieldTreatmentCost, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(0, 0, Short.MAX_VALUE))))
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(324, 324, 324)
                .addComponent(lblMedicalResult)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnBack))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPet)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldPetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPetName))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldSpieces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSpecies))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblAge))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblWeight)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblInsuranceCompany)
                            .addComponent(fieldInsuranceCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPolicyID)
                            .addComponent(fieldPolicyID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCoverageLevel)
                            .addComponent(comboCoverageLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblExpirationDate)
                            .addComponent(fieldExpirationDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldFoodAllergy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFoodAllergy))
                .addGap(19, 19, 19)
                .addComponent(lblMedicalResult)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLabTestResult)
                    .addComponent(fieldLabTestResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTreatmentNeeded)
                    .addComponent(comboTreatmentNeeded, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTreatmentCost)
                    .addComponent(fieldTreatmentCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(btnSubmitInsuranceClaimRequest)
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSubmitInsuranceClaimRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitInsuranceClaimRequestActionPerformed
        // TODO add your handling code here:
        try {
            
        //把治疗数据写回 HealthCareCheckRequest
        Request.setTreatmentNeeded((String) comboTreatmentNeeded.getSelectedItem());
        Request.setTreatmentCost(Double.parseDouble(fieldTreatmentCost.getText()));
        
        InsuranceClaimRequest claimRequest = new InsuranceClaimRequest();
        
        //Basic Info 
        Pet p = Request.getPet();
        claimRequest.setPatientId(p.getPetId());
        claimRequest.setPolicyId(p.getPetOwner().getPolicyId());
        claimRequest.setHolderName(p.getPetOwner().getOwnerName());
        claimRequest.setPetName(p.getPetName());
        
        //设置Pet和Owner对象
        claimRequest.setPet(p);
        claimRequest.setOwner(p.getPetOwner());
        
        //设置Treatment Needed（从下拉框获取）
        String treatmentNeeded = (String) comboTreatmentNeeded.getSelectedItem();
        claimRequest.setTreatmentNeeded(treatmentNeeded);
        
        //设置DoctorName
        if (Request.getAssignedDoctor() != null) {
            claimRequest.setDoctorName(Request.getAssignedDoctor());
        }
        
        //TreatmentCost
        double treatmentCost = Double.parseDouble(fieldTreatmentCost.getText());
        
        //Medical Info
        claimRequest.setSymptom(Request.getSymptom());
        claimRequest.setLabResult(Request.getLabResult());
        claimRequest.setTreatmentCost(treatmentCost);
        
        //Insurance Info
        claimRequest.setInsuranceCompany(p.getPetOwner().getInsuranceCompany());
        claimRequest.setCoverageLevel((String) comboCoverageLevel.getSelectedItem());
        claimRequest.setExpirationDate(p.getPetOwner().getExpirationDate());
        claimRequest.setClaimAmount(0.0);  // initial
        claimRequest.setClaimDecision("Pending");
        claimRequest.setStatus("Pending");
        
        // Relationship to Clinic Request
        claimRequest.setHealthRequest(Request);
        
        //建立双向关联
        Request.setInsuranceClaimRequest(claimRequest);
        
        //同时更新HealthCareCheckRequest的Treatment信息
        Request.setTreatmentNeeded(treatmentNeeded);
        Request.setTreatmentCost(treatmentCost);
        
        //Sender
        claimRequest.setSender(account);
        claimRequest.setMessage("Insurance claim for patient: " + p.getPetId());
        
        //Find the Insurance Claim Org
        Organization claimOrg = null;
        for (Organization org : insuranceEnterprise.getOrganizationDirectory().getOrganizationList()) {
            if (org instanceof InsuranceClaimOrganization) {
                claimOrg = org;
                break;
            }
        }
        
        if (claimOrg != null) {
            claimOrg.getWorkQueue().getWorkRequestList().add(claimRequest);
            account.getWorkQueue().getWorkRequestList().add(claimRequest);
            
            frontDeskOrg.getWorkQueue().getWorkRequestList().add(claimRequest);

            //发送到 Pet Boarding Customer Service 
            sendToCustomerService(Request);
            
            JOptionPane.showMessageDialog(this,
                "Insurance Claim Request submitted successfully!\n" +
                "Treatment: " + treatmentNeeded + "\n" +
                "Cost: $" + String.format("%.2f", treatmentCost) + "\n" +
                "Notification sent to Customer Service.",
                "Success",
                JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this,
                "Insurance Claim Organization not found!",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Please check the treatment cost input.\nError: " + e.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
       
}



//发送到 Customer Service
private void sendToCustomerService(HealthCareCheckRequest healthRequest) {
    //获取系统实例
    Business.Petsystem system = Business.Petsystem.getInstance();
    
    //遍历所有网络，查找Pet Boarding Enterprise的Customer Service Organization
    for (Business.Network.Network network : system.getNetworkList()) {
        for (Business.Enterprise.Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
            //找到Pet Boarding Enterprise
            if (enterprise instanceof Business.Enterprise.PetBoardingEnterprise) {
                for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
                    //找到Customer Service Organization
                    if (org instanceof Business.PetBoardingOrganization.CustomerService) {
                        //把HealthCareCheckRequest添加到Customer Service的队列
                        org.getWorkQueue().getWorkRequestList().add(healthRequest);
                        System.out.println("✅ Request sent to Customer Service: " + healthRequest.getPatientId());
                        return;
                    }
                }
            }
        }
    }
    System.out.println("⚠️ Customer Service Organization not found!");
        
    }//GEN-LAST:event_btnSubmitInsuranceClaimRequestActionPerformed

    private void comboTreatmentNeededActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTreatmentNeededActionPerformed
        // TODO add your handling code here:
         updateTreatmentCost();

    }//GEN-LAST:event_comboTreatmentNeededActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSubmitInsuranceClaimRequest;
    private javax.swing.JComboBox<String> comboCoverageLevel;
    private javax.swing.JComboBox<String> comboTreatmentNeeded;
    private javax.swing.JTextField fieldAge;
    private javax.swing.JTextField fieldExpirationDate;
    private javax.swing.JTextField fieldFoodAllergy;
    private javax.swing.JTextField fieldInsuranceCompany;
    private javax.swing.JTextField fieldLabTestResult;
    private javax.swing.JTextField fieldPetName;
    private javax.swing.JTextField fieldPolicyID;
    private javax.swing.JTextField fieldSpieces;
    private javax.swing.JTextField fieldTreatmentCost;
    private javax.swing.JTextField fieldWeight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCoverageLevel;
    private javax.swing.JLabel lblExpirationDate;
    private javax.swing.JLabel lblFoodAllergy;
    private javax.swing.JLabel lblInsuranceCompany;
    private javax.swing.JLabel lblLabTestResult;
    private javax.swing.JLabel lblMedicalResult;
    private javax.swing.JLabel lblPet;
    private javax.swing.JLabel lblPetName;
    private javax.swing.JLabel lblPolicyID;
    private javax.swing.JLabel lblSpecies;
    private javax.swing.JLabel lblTreatmentCost;
    private javax.swing.JLabel lblTreatmentNeeded;
    private javax.swing.JLabel lblWeight;
    // End of variables declaration//GEN-END:variables

    private void populateData() {
    
    //获取宠物对象    
    Pet p = Request.getPet();
    //Pet info
    fieldPetName.setText(p.getPetName());
    fieldSpieces.setText(p.getSpecies());
    fieldAge.setText(String.valueOf(p.getAge()));
    fieldWeight.setText(String.valueOf(p.getWeight()));
    fieldFoodAllergy.setText(p.getFoodAllergy());

    //Insurance info
    fieldInsuranceCompany.setText(p.getPetOwner().getInsuranceCompany());
    fieldPolicyID.setText(p.getPetOwner().getPolicyId());
    comboCoverageLevel.setSelectedItem(p.getPetOwner().getCoverageLevel());
    fieldExpirationDate.setText(p.getPetOwner().getExpirationDate());


    //Medical Result (来自Pet Clinic)
    fieldLabTestResult.setText(Request.getLabResult());
    comboTreatmentNeeded.setSelectedItem(Request.getTreatmentNeeded());
    updateTreatmentCost(); //自动根据 map 设置价格
    
    
    disableAllFields();
    }

    
    private void disableAllFields() {
    
    fieldPetName.setEnabled(false);
    fieldSpieces.setEnabled(false);
    fieldAge.setEnabled(false);
    fieldWeight.setEnabled(false);
    fieldFoodAllergy.setEnabled(false);

    fieldInsuranceCompany.setEnabled(false);
    fieldPolicyID.setEnabled(false);
    fieldExpirationDate.setEnabled(false);
    comboCoverageLevel.setEnabled(false);

    

    fieldLabTestResult.setEnabled(false);
    comboTreatmentNeeded.setEnabled(false);
    fieldTreatmentCost.setEnabled(false);
    }

    private void initTreatmentPrice() {
        
        treatmentPriceMap.put("Medication Only ", 80.0);
        treatmentPriceMap.put("IV Fluids & Supportive Care ", 250.0);
        treatmentPriceMap.put("Diagnostic Imaging (X-ray / Ultrasound) ", 400.0);
        treatmentPriceMap.put("Surgery ", 1200.0);
        treatmentPriceMap.put("Hospitalization ", 600.0);
    }

    private void updateTreatmentCost() {
        String selected = (String) comboTreatmentNeeded.getSelectedItem();
        if (selected != null && treatmentPriceMap.containsKey(selected)) {
            fieldTreatmentCost.setText(String.valueOf(treatmentPriceMap.get(selected)));
        }
    }
}
