/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Boarding;

import Business.Enterprise.Enterprise;
import Business.PetBoardingOrganization.CustomerService;
import Business.Pet.Pet;
import Business.Pet.PetOwner;
import Business.Petsystem;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.HealthCareCheckRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import Business.WorkQueue.InsuranceClaimRequest;
import Business.Pet.PetBoardingRecord;
import Business.Enterprise.PetBoardingEnterprise;
import Business.Network.Network;
/**
 *
 * @author hanlinyao
 */
public class CSViewJPanel extends javax.swing.JPanel {
    
    // 成员变量
    private JPanel userProcessContainer;
    private UserAccount account;
    private CustomerService organization;
    private Enterprise enterprise;
    private Petsystem system;
    private HealthCareCheckRequest selectedRequest;

    /**
     * Creates new form CSViewJPanel
     */
    public CSViewJPanel(JPanel userProcessContainer, UserAccount account,
                        CustomerService organization, Enterprise enterprise, Petsystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;  // ⭐ 必须赋值
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;
        
         // 设置所有字段为只读
        setFieldsEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBoarding = new javax.swing.JLabel();
        lblCoverage = new javax.swing.JLabel();
        fieldEmail = new javax.swing.JTextField();
        fieldFood = new javax.swing.JTextField();
        lblRoom = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblSD = new javax.swing.JLabel();
        fieldPetName = new javax.swing.JTextField();
        fieldCompany = new javax.swing.JTextField();
        lblPet = new javax.swing.JLabel();
        lblED = new javax.swing.JLabel();
        fieldSpecies = new javax.swing.JTextField();
        fieldPolicy = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        fieldAge = new javax.swing.JTextField();
        lblPetName = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblSpecies = new javax.swing.JLabel();
        fieldCL = new javax.swing.JTextField();
        fieldRoom = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        lblAddress = new javax.swing.JLabel();
        lblPetowner = new javax.swing.JLabel();
        fieldSD = new javax.swing.JTextField();
        lblContact = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        fieldContact = new javax.swing.JTextField();
        fieldED = new javax.swing.JTextField();
        fieldWeight = new javax.swing.JTextField();
        lblInsurance = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblEp = new javax.swing.JLabel();
        lblWeight = new javax.swing.JLabel();
        fieldOwnerName = new javax.swing.JTextField();
        lblCompany = new javax.swing.JLabel();
        fieldEp = new javax.swing.JTextField();
        fieldPhone = new javax.swing.JTextField();
        lblPolicy = new javax.swing.JLabel();
        fieldAddress = new javax.swing.JTextField();
        lblFood = new javax.swing.JLabel();
        lblSymptom = new javax.swing.JLabel();
        fieldSymptom = new javax.swing.JTextField();
        lblHealthCheckStatus = new javax.swing.JLabel();
        lblTreatmentNeeded = new javax.swing.JLabel();
        lblTreatmentCost = new javax.swing.JLabel();
        lblInsuranceStatus = new javax.swing.JLabel();
        lblInsuranceCost = new javax.swing.JLabel();
        fieldHealthStatus = new javax.swing.JTextField();
        fieldTreatmentNeeded = new javax.swing.JTextField();
        fieldTreatmentCost = new javax.swing.JTextField();
        fieldInsuranceStatus = new javax.swing.JTextField();
        fieldInsuranceCost = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 204));

        lblBoarding.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblBoarding.setForeground(new java.awt.Color(0, 51, 255));
        lblBoarding.setText("Boarding");

        lblCoverage.setText("Coverage Level");

        fieldFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldFoodActionPerformed(evt);
            }
        });

        lblRoom.setText("Room Number");

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTitle.setText("View Details");

        lblSD.setText("Start Date");

        lblPet.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblPet.setForeground(new java.awt.Color(0, 51, 255));
        lblPet.setText("Pet");

        lblED.setText("End Date");

        lblName.setText("Name");

        lblPetName.setText("Pet Name");

        lblPhone.setText("Phone No");

        lblSpecies.setText("Species");

        btnBack.setText("<<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblAddress.setText("Address");

        lblPetowner.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblPetowner.setForeground(new java.awt.Color(0, 51, 255));
        lblPetowner.setText("Pet Owner");

        lblContact.setText("Emergency Contact");

        lblEmail.setText("Email");

        fieldWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldWeightActionPerformed(evt);
            }
        });

        lblInsurance.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblInsurance.setForeground(new java.awt.Color(0, 102, 255));
        lblInsurance.setText("Insurance");

        lblAge.setText("Age");

        lblEp.setText("Expiration Date");

        lblWeight.setText("Weight");

        lblCompany.setText("Insurance Company");

        lblPolicy.setText("Policy No");

        fieldAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldAddressActionPerformed(evt);
            }
        });

        lblFood.setText("Food Allergy");

        lblSymptom.setText("Symptom");

        lblHealthCheckStatus.setText("Health Check Status");

        lblTreatmentNeeded.setText("Treatment Needed");

        lblTreatmentCost.setText("Treatment Cost");

        lblInsuranceStatus.setText("Insurance Status");

        lblInsuranceCost.setText("Insurance Cost");

        fieldInsuranceStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldInsuranceStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblFood)
                                    .addComponent(lblSpecies)
                                    .addComponent(lblPetName)
                                    .addComponent(lblRoom)
                                    .addComponent(lblAge)
                                    .addComponent(lblWeight)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblED)
                                        .addComponent(lblSD)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fieldSpecies, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fieldPetName, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fieldWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fieldFood, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(22, 22, 22)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(fieldRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fieldSD, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fieldED, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblPet)
                                .addGap(119, 119, 119))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(lblBoarding)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblName, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPhone, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fieldOwnerName)
                                    .addComponent(fieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblContact)
                                .addGap(50, 50, 50)
                                .addComponent(fieldContact, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblAddress, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblPetowner)
                                .addGap(110, 110, 110)))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSymptom)
                            .addComponent(lblHealthCheckStatus)
                            .addComponent(lblTreatmentNeeded)
                            .addComponent(lblTreatmentCost)
                            .addComponent(lblInsuranceStatus)
                            .addComponent(lblInsuranceCost))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldSymptom, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(fieldHealthStatus)
                            .addComponent(fieldTreatmentNeeded)
                            .addComponent(fieldTreatmentCost)
                            .addComponent(fieldInsuranceStatus)
                            .addComponent(fieldInsuranceCost))
                        .addGap(58, 58, 58))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(lblInsurance)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCoverage)
                                    .addComponent(lblEp))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldCL)
                                    .addComponent(fieldEp)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCompany)
                                    .addComponent(lblPolicy))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldPolicy)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fieldCompany, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                        .addContainerGap())))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(366, 366, 366)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle)
                    .addComponent(btnBack))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSymptom)
                            .addComponent(fieldSymptom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHealthCheckStatus)
                            .addComponent(fieldHealthStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTreatmentNeeded)
                            .addComponent(fieldTreatmentNeeded, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTreatmentCost)
                            .addComponent(fieldTreatmentCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblInsuranceStatus)
                            .addComponent(fieldInsuranceStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblInsuranceCost)
                            .addComponent(fieldInsuranceCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 257, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPetName)
                                    .addComponent(fieldPetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblSpecies)
                                    .addComponent(fieldSpecies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblAge)
                                    .addComponent(fieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblWeight)
                                    .addComponent(fieldWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblFood)
                                    .addComponent(fieldFood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPet)
                                    .addComponent(lblPetowner))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblName)
                                    .addComponent(fieldOwnerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPhone)
                                    .addComponent(fieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblAddress)
                                    .addComponent(fieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblEmail)
                                    .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblContact)
                                    .addComponent(fieldContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRoom)
                                    .addComponent(fieldRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fieldSD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSD))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(fieldED, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblED))
                                .addGap(61, 61, 61))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblInsurance)
                                    .addComponent(lblBoarding))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCompany)
                                    .addComponent(fieldCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPolicy)
                                    .addComponent(fieldPolicy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCoverage)
                                    .addComponent(fieldCL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblEp)
                                    .addComponent(fieldEp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38))))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldFoodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldFoodActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
       userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void fieldWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldWeightActionPerformed

    private void fieldAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldAddressActionPerformed

    private void fieldInsuranceStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldInsuranceStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldInsuranceStatusActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JTextField fieldAddress;
    private javax.swing.JTextField fieldAge;
    private javax.swing.JTextField fieldCL;
    private javax.swing.JTextField fieldCompany;
    private javax.swing.JTextField fieldContact;
    private javax.swing.JTextField fieldED;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JTextField fieldEp;
    private javax.swing.JTextField fieldFood;
    private javax.swing.JTextField fieldHealthStatus;
    private javax.swing.JTextField fieldInsuranceCost;
    private javax.swing.JTextField fieldInsuranceStatus;
    private javax.swing.JTextField fieldOwnerName;
    private javax.swing.JTextField fieldPetName;
    private javax.swing.JTextField fieldPhone;
    private javax.swing.JTextField fieldPolicy;
    private javax.swing.JTextField fieldRoom;
    private javax.swing.JTextField fieldSD;
    private javax.swing.JTextField fieldSpecies;
    private javax.swing.JTextField fieldSymptom;
    private javax.swing.JTextField fieldTreatmentCost;
    private javax.swing.JTextField fieldTreatmentNeeded;
    private javax.swing.JTextField fieldWeight;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblBoarding;
    private javax.swing.JLabel lblCompany;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblCoverage;
    private javax.swing.JLabel lblED;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEp;
    private javax.swing.JLabel lblFood;
    private javax.swing.JLabel lblHealthCheckStatus;
    private javax.swing.JLabel lblInsurance;
    private javax.swing.JLabel lblInsuranceCost;
    private javax.swing.JLabel lblInsuranceStatus;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPet;
    private javax.swing.JLabel lblPetName;
    private javax.swing.JLabel lblPetowner;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPolicy;
    private javax.swing.JLabel lblRoom;
    private javax.swing.JLabel lblSD;
    private javax.swing.JLabel lblSpecies;
    private javax.swing.JLabel lblSymptom;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTreatmentCost;
    private javax.swing.JLabel lblTreatmentNeeded;
    private javax.swing.JLabel lblWeight;
    // End of variables declaration//GEN-END:variables
    public void loadRequestDetails(HealthCareCheckRequest request) {
        // ⭐ 添加调试输出
    System.out.println("=== DEBUG CSViewJPanel ===");
    System.out.println("Boarding Record ID: " + request.getBoardingRecordId());
    System.out.println("System: " + system);
       
    this.selectedRequest = request;
    if (request == null) return;

    Pet pet = request.getPet();
    PetOwner owner = (pet != null) ? pet.getPetOwner() : null;
    
    // 获取关联的 InsuranceClaimRequest（如果有）
    InsuranceClaimRequest claimRequest = request.getInsuranceClaimRequest();

    // ========== 宠物信息 (Pet) ==========
    fieldPetName.setText((pet != null) ? pet.getPetName() : "N/A");
    fieldSpecies.setText((pet != null) ? pet.getSpecies() : "N/A");
    fieldAge.setText((pet != null) ? String.valueOf(pet.getAge()) : "N/A");
    fieldWeight.setText((pet != null) ? String.valueOf(pet.getWeight()) : "N/A");
    fieldFood.setText((pet != null && pet.getFoodAllergy() != null) ? pet.getFoodAllergy() : "N/A");

    // ========== 宠物主人信息 (Pet Owner) ==========
    fieldOwnerName.setText((owner != null) ? owner.getOwnerName() : "N/A");
    fieldPhone.setText((owner != null) ? owner.getPhone() : "N/A");
    fieldEmail.setText((owner != null) ? owner.getEmail() : "N/A");
    fieldAddress.setText((owner != null) ? owner.getAddress() : "N/A");
    fieldContact.setText((owner != null) ? owner.getEmergencyContact() : "N/A");

    // ========== 保险信息 (Insurance) ==========
    fieldCompany.setText((owner != null && owner.getInsuranceCompany() != null) ? owner.getInsuranceCompany() : "N/A");
    fieldPolicy.setText((owner != null && owner.getPolicyId() != null) ? owner.getPolicyId() : "N/A");
    
    // Coverage Level - 优先从 claimRequest 获取
    if (claimRequest != null && claimRequest.getCoverageLevel() != null) {
        fieldCL.setText(claimRequest.getCoverageLevel());
    } else if (owner != null && owner.getCoverageLevel() != null) {
        fieldCL.setText(owner.getCoverageLevel());
    } else {
        fieldCL.setText("N/A");
    }
    
    fieldEp.setText((owner != null && owner.getExpirationDate() != null) ? owner.getExpirationDate() : "N/A");

    String roomNumber = "N/A";
String startDate = "N/A";
String endDate = "N/A";

System.out.println("Looking for BoardingRecord with ID: " + request.getBoardingRecordId());

if (request.getBoardingRecordId() != null && system != null) {
    System.out.println("Network count: " + system.getNetworkList().size());
    
    for (Business.Network.Network network : system.getNetworkList()) {
        System.out.println("  Network: " + network.getName());
        
        for (Business.Enterprise.Enterprise ent : network.getEnterpriseDirectory().getEnterpriseList()) {
            System.out.println("    Enterprise: " + ent.getName() + " [" + ent.getClass().getSimpleName() + "]");
            
            if (ent instanceof Business.Enterprise.PetBoardingEnterprise) {
                Business.Enterprise.PetBoardingEnterprise boardingEnt = (Business.Enterprise.PetBoardingEnterprise) ent;
                
                // 打印所有记录
                System.out.println("    Total records: " + boardingEnt.getBoardingRecordDirectory().getRecordList().size());
                for (Business.Pet.PetBoardingRecord rec : boardingEnt.getBoardingRecordDirectory().getRecordList()) {
                    System.out.println("      - Record ID: " + rec.getRecordId());
                }
                
                Business.Pet.PetBoardingRecord record = boardingEnt.getBoardingRecordDirectory().findRecordById(request.getBoardingRecordId());
                System.out.println("    Found record: " + record);
                
                if (record != null) {
                    roomNumber = record.getRoomNumber() != null ? record.getRoomNumber() : "N/A";
                    startDate = record.getStartDate() != null ? record.getStartDate() : "N/A";
                    endDate = record.getEndDate() != null ? record.getEndDate() : "N/A";
                    System.out.println("    ✅ Room: " + roomNumber + ", Start: " + startDate + ", End: " + endDate);
                    break;
                }
            }
        }
    }
} else {
    System.out.println("⚠️ BoardingRecordId is null or system is null!");
}

fieldRoom.setText(roomNumber);
fieldSD.setText(startDate);
fieldED.setText(endDate);

    // ========== ⭐ 医疗信息 (Medical Info) - 新增 ⭐ ==========
    // 注意：需要先在 GUI 设计器中添加这些字段
    
    // Symptom
    if (fieldSymptom != null) {
        fieldSymptom.setText(request.getSymptom() != null ? request.getSymptom() : "N/A");
    }
    
    // Health Check Status
    if (fieldHealthStatus != null) {
        fieldHealthStatus.setText(request.getStatus() != null ? request.getStatus() : "N/A");
    }
    
    // Treatment Needed - 优先从 claimRequest 获取
    if (fieldTreatmentNeeded != null) {
        String treatmentNeeded = "N/A";
        if (claimRequest != null && claimRequest.getTreatmentNeeded() != null) {
            treatmentNeeded = claimRequest.getTreatmentNeeded();
        } else if (request.getTreatmentNeeded() != null) {
            treatmentNeeded = request.getTreatmentNeeded();
        }
        fieldTreatmentNeeded.setText(treatmentNeeded);
    }
    
    // Treatment Cost - 优先从 claimRequest 获取
    if (fieldTreatmentCost != null) {
        double cost = 0;
        if (claimRequest != null && claimRequest.getTreatmentCost() > 0) {
            cost = claimRequest.getTreatmentCost();
        } else if (request.getTreatmentCost() > 0) {
            cost = request.getTreatmentCost();
        }
        fieldTreatmentCost.setText(cost > 0 ? String.format("$%.2f", cost) : "N/A");
    }
    
    // Insurance Status (Claim Decision)
    if (fieldInsuranceStatus != null) {
        String status = "No Claim";
        if (claimRequest != null && claimRequest.getClaimDecision() != null) {
            status = claimRequest.getClaimDecision();
        }
        fieldInsuranceStatus.setText(status);
    }
    
    // Insurance Cost (Claim Amount)
    if (fieldInsuranceCost != null) {
        String costStr = "N/A";
        if (claimRequest != null && claimRequest.getClaimAmount() > 0) {
            costStr = String.format("$%.2f", claimRequest.getClaimAmount());
        }
        fieldInsuranceCost.setText(costStr);
    }
}

// ⭐ 更新 setFieldsEditable 方法 - 添加新字段
private void setFieldsEditable(boolean editable) {
    // 原有字段
    fieldPetName.setEditable(editable);
    fieldSpecies.setEditable(editable);
    fieldAge.setEditable(editable);
    fieldWeight.setEditable(editable);
    fieldFood.setEditable(editable);
    
    fieldOwnerName.setEditable(editable);
    fieldPhone.setEditable(editable);
    fieldEmail.setEditable(editable);
    fieldAddress.setEditable(editable);
    fieldContact.setEditable(editable);
    
    fieldCompany.setEditable(editable);
    fieldPolicy.setEditable(editable);
    fieldCL.setEditable(editable);
    fieldEp.setEditable(editable);
    
    fieldRoom.setEditable(editable);
    fieldSD.setEditable(editable);
    fieldED.setEditable(editable);
    
   
     fieldSymptom.setEditable(editable);
     fieldHealthStatus.setEditable(editable);
     fieldTreatmentNeeded.setEditable(editable);
    fieldTreatmentCost.setEditable(editable);
    fieldInsuranceStatus.setEditable(editable);
     fieldInsuranceCost.setEditable(editable);
     
}
}