/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Boarding;

import Business.Enterprise.Enterprise;
import Business.PetBoardingOrganization.CustomerService;
import Business.Pet.Pet;
import Business.Pet.PetOwner;
import Business.Petsystem;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.HealthCareCheckRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author hanlinyao
 */
public class CSViewJPanel extends javax.swing.JPanel {
    
    // 成员变量
    private JPanel userProcessContainer;
    private UserAccount account;
    private CustomerService organization;
    private Enterprise enterprise;
    private Petsystem system;
    private HealthCareCheckRequest selectedRequest;

    /**
     * Creates new form CSViewJPanel
     */
    public CSViewJPanel(JPanel userProcessContainer, UserAccount account,
                        CustomerService organization, Enterprise enterprise, Petsystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;  // ⭐ 必须赋值
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;
        
         // 设置所有字段为只读
        setFieldsEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBoarding = new javax.swing.JLabel();
        lblCoverage = new javax.swing.JLabel();
        fieldEmail = new javax.swing.JTextField();
        fieldFood = new javax.swing.JTextField();
        lblRoom = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblSD = new javax.swing.JLabel();
        fieldPetName = new javax.swing.JTextField();
        fieldCompany = new javax.swing.JTextField();
        lblPet = new javax.swing.JLabel();
        lblED = new javax.swing.JLabel();
        fieldSpecies = new javax.swing.JTextField();
        fieldPolicy = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        fieldAge = new javax.swing.JTextField();
        lblPetName = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblSpecies = new javax.swing.JLabel();
        fieldCL = new javax.swing.JTextField();
        fieldRoom = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        lblAddress = new javax.swing.JLabel();
        lblPetowner = new javax.swing.JLabel();
        fieldSD = new javax.swing.JTextField();
        lblContact = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        fieldContact = new javax.swing.JTextField();
        fieldED = new javax.swing.JTextField();
        fieldWeight = new javax.swing.JTextField();
        lblInsurance = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblEp = new javax.swing.JLabel();
        lblWeight = new javax.swing.JLabel();
        fieldOwnerName = new javax.swing.JTextField();
        lblCompany = new javax.swing.JLabel();
        fieldEp = new javax.swing.JTextField();
        fieldPhone = new javax.swing.JTextField();
        lblPolicy = new javax.swing.JLabel();
        fieldAddress = new javax.swing.JTextField();
        lblFood = new javax.swing.JLabel();

        lblBoarding.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblBoarding.setForeground(new java.awt.Color(0, 51, 255));
        lblBoarding.setText("Boarding");

        lblCoverage.setText("Coverage Level");

        fieldFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldFoodActionPerformed(evt);
            }
        });

        lblRoom.setText("Room Number");

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblTitle.setText("View Details");

        lblSD.setText("Start Date");

        lblPet.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblPet.setForeground(new java.awt.Color(0, 51, 255));
        lblPet.setText("Pet");

        lblED.setText("End Date");

        lblName.setText("Name");

        lblPetName.setText("Pet Name");

        lblPhone.setText("Phone No");

        lblSpecies.setText("Species");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblAddress.setText("Address");

        lblPetowner.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblPetowner.setForeground(new java.awt.Color(0, 51, 255));
        lblPetowner.setText("Pet Owner");

        lblContact.setText("Emergency Contact");

        lblEmail.setText("Email");

        fieldWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldWeightActionPerformed(evt);
            }
        });

        lblInsurance.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblInsurance.setForeground(new java.awt.Color(0, 102, 255));
        lblInsurance.setText("Insurance");

        lblAge.setText("Age");

        lblEp.setText("Expiration Date");

        lblWeight.setText("Weight");

        lblCompany.setText("Insurance Company");

        lblPolicy.setText("Policy No");

        fieldAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldAddressActionPerformed(evt);
            }
        });

        lblFood.setText("Food Allergy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(296, 296, 296)
                .addComponent(lblTitle)
                .addContainerGap(307, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblPetName)
                                    .addGap(64, 64, 64)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fieldSpecies, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fieldPetName, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fieldWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblFood)
                                    .addGap(49, 49, 49)
                                    .addComponent(fieldFood, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblSpecies)
                                .addComponent(lblAge)
                                .addComponent(lblWeight)
                                .addComponent(lblED)
                                .addComponent(lblSD)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(106, 106, 106)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(fieldRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fieldSD, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fieldED, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(lblPet)
                                .addComponent(lblBoarding)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnBack)
                                    .addComponent(lblRoom)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(202, 202, 202)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblAddress)
                                                .addComponent(lblEmail))
                                            .addGap(33, 33, 33)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(fieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblPhone)
                                                .addComponent(lblName))
                                            .addGap(26, 26, 26)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(fieldOwnerName, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                                .addComponent(fieldPhone)))
                                        .addComponent(lblPetowner)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(210, 210, 210)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblInsurance)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblPolicy)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(fieldPolicy, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblCompany)
                                                .addGap(18, 18, 18)
                                                .addComponent(fieldCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblCoverage)
                                                    .addComponent(lblEp))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(fieldCL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(fieldEp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblContact)
                                    .addGap(49, 49, 49)
                                    .addComponent(fieldContact, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(32, 32, 32)))
                            .addContainerGap(14, Short.MAX_VALUE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitle)
                .addGap(0, 526, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(btnBack)
                    .addGap(31, 31, 31)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblInsurance)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblCompany)
                                .addComponent(fieldCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblPolicy)
                                .addComponent(fieldPolicy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(17, 17, 17)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblCoverage)
                                .addComponent(fieldCL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblPet)
                                .addComponent(lblPetowner))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblPetName)
                                .addComponent(lblName)
                                .addComponent(fieldPetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fieldOwnerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblSpecies)
                                .addComponent(lblPhone)
                                .addComponent(fieldSpecies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblAge)
                                .addComponent(lblAddress)
                                .addComponent(fieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblWeight)
                                .addComponent(lblEmail)
                                .addComponent(fieldWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblContact)
                                    .addComponent(fieldContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblFood)
                                    .addComponent(fieldFood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(88, 88, 88)
                            .addComponent(lblBoarding)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblRoom)
                                .addComponent(fieldRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblSD)
                                .addComponent(fieldSD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(17, 17, 17)
                                    .addComponent(lblED))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(fieldED, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblEp)
                        .addComponent(fieldEp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldFoodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldFoodActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
       userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void fieldWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldWeightActionPerformed

    private void fieldAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldAddressActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JTextField fieldAddress;
    private javax.swing.JTextField fieldAge;
    private javax.swing.JTextField fieldCL;
    private javax.swing.JTextField fieldCompany;
    private javax.swing.JTextField fieldContact;
    private javax.swing.JTextField fieldED;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JTextField fieldEp;
    private javax.swing.JTextField fieldFood;
    private javax.swing.JTextField fieldOwnerName;
    private javax.swing.JTextField fieldPetName;
    private javax.swing.JTextField fieldPhone;
    private javax.swing.JTextField fieldPolicy;
    private javax.swing.JTextField fieldRoom;
    private javax.swing.JTextField fieldSD;
    private javax.swing.JTextField fieldSpecies;
    private javax.swing.JTextField fieldWeight;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblBoarding;
    private javax.swing.JLabel lblCompany;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblCoverage;
    private javax.swing.JLabel lblED;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEp;
    private javax.swing.JLabel lblFood;
    private javax.swing.JLabel lblInsurance;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPet;
    private javax.swing.JLabel lblPetName;
    private javax.swing.JLabel lblPetowner;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPolicy;
    private javax.swing.JLabel lblRoom;
    private javax.swing.JLabel lblSD;
    private javax.swing.JLabel lblSpecies;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWeight;
    // End of variables declaration//GEN-END:variables
    public void loadRequestDetails(HealthCareCheckRequest request) {
        this.selectedRequest = request;
        if (request == null) return;

        Pet pet = request.getPet();
        PetOwner owner = (pet != null) ? pet.getPetOwner() : null;

        // 宠物信息 (Pet)
        fieldPetName.setText((pet != null) ? pet.getPetName() : "N/A");
        fieldSpecies.setText((pet != null) ? pet.getSpecies() : "N/A");
        fieldAge.setText((pet != null) ? String.valueOf(pet.getAge()) : "N/A");
        fieldWeight.setText((pet != null) ? String.valueOf(pet.getWeight()) : "N/A");
        fieldFood.setText((pet != null && pet.getFoodAllergy() != null) ? pet.getFoodAllergy() : "N/A");

        // 宠物主人信息 (Pet Owner)
        fieldOwnerName.setText((owner != null) ? owner.getOwnerName() : "N/A");
        fieldPhone.setText((owner != null) ? owner.getPhone() : "N/A");
        fieldEmail.setText((owner != null) ? owner.getEmail() : "N/A");
        fieldAddress.setText((owner != null) ? owner.getAddress() : "N/A");
        fieldContact.setText((owner != null) ? owner.getEmergencyContact() : "N/A");

        // 保险信息 (Insurance) - 从 PetOwner 获取
        fieldCompany.setText((owner != null && owner.getInsuranceCompany() != null) ? owner.getInsuranceCompany() : "N/A");
        fieldPolicy.setText((owner != null && owner.getPolicyId() != null) ? owner.getPolicyId() : "N/A");
        fieldCL.setText((owner != null && owner.getCoverageLevel() != null) ? owner.getCoverageLevel() : "N/A");
        fieldEp.setText((owner != null && owner.getExpirationDate() != null) ? owner.getExpirationDate() : "N/A");

        // 寄养信息 (Boarding) - 如果有关联的 BoardingRecord
        // 注意：HealthCareCheckRequest 可能没有直接关联 BoardingRecord，这里简化处理
        fieldRoom.setText(request.getBoardingRecordId() != null ? request.getBoardingRecordId() : "N/A");
        fieldSD.setText("N/A");  // 如果需要显示，需要从 BoardingRecord 获取
        fieldED.setText("N/A");  // 如果需要显示，需要从 BoardingRecord 获取
    }
    
    private void setFieldsEditable(boolean editable) {
        fieldPetName.setEditable(editable);
        fieldSpecies.setEditable(editable);
        fieldAge.setEditable(editable);
        fieldWeight.setEditable(editable);
        fieldFood.setEditable(editable);
        
        fieldOwnerName.setEditable(editable);
        fieldPhone.setEditable(editable);
        fieldEmail.setEditable(editable);
        fieldAddress.setEditable(editable);
        fieldContact.setEditable(editable);
        
        fieldCompany.setEditable(editable);
        fieldPolicy.setEditable(editable);
        fieldCL.setEditable(editable);
        fieldEp.setEditable(editable);
        
        fieldRoom.setEditable(editable);
        fieldSD.setEditable(editable);
        fieldED.setEditable(editable);
    }
}
