/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Boarding;

import Business.Enterprise.Enterprise;
import Business.Enterprise.PetBoardingEnterprise;
import Business.Organization.Organization;
import Business.Pet.BoardingRecordDirectory;
import Business.Pet.Pet;
import Business.Pet.PetBoardingRecord;
import Business.Petsystem;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.HealthCareCheckRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import Business.PetBoardingOrganization.CustomerService;
import java.text.SimpleDateFormat;

/**
 *
 * @author hanlinyao
 */
public class ManagerJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private UserAccount account;
    private Organization organization;
    private Enterprise enterprise;
    private Petsystem system;
    
    private final SimpleDateFormat FULL_DATE_FORMAT = new SimpleDateFormat("EEE MMM dd HH:mm:ss zzz yyyy");
    private final SimpleDateFormat YEAR_DATE_FORMAT = new SimpleDateFormat("yyyy");

    /**
     * Creates new form ManageJPanel
     */
   public ManagerJPanel(JPanel userProcessContainer, UserAccount account, 
                             Organization organization, Enterprise enterprise, Petsystem system) {
        
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;
        initComponents();
        
        // 初始化表格
        populateTable();
        //现实运营数据
        calculateOperationIndicators();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        btnSend = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblor = new javax.swing.JLabel();
        fieldor = new javax.swing.JTextField();
        lblnc = new javax.swing.JLabel();
        lbldd = new javax.swing.JLabel();
        lbltr = new javax.swing.JLabel();
        lblir = new javax.swing.JLabel();
        lbls = new javax.swing.JLabel();
        fieldnc = new javax.swing.JTextField();
        fielddd = new javax.swing.JTextField();
        fieldtr = new javax.swing.JTextField();
        fieldir = new javax.swing.JTextField();
        fields = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setText("Welcome to Pet Boarding Manager Work Area");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Record ID", "Species", "Breakfast", "Lunch", "Dinner", "Poop", "Mood", "Symptom", "Message"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnView.setText("View Details");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnSend.setText("Send to Customer service");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel2.setText("Operation Indicators Report");

        lblor.setText("Occupancy Rate");

        lblnc.setText("New Check-ins");

        lbldd.setText("Dog/Cat-Days");

        lbltr.setText("Total Revenue");

        lblir.setText("Incident Rate");

        lbls.setText("Staff-to-Dog Ratio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(82, 82, 82))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(btnView)
                        .addGap(202, 202, 202)
                        .addComponent(btnSend))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblor)
                                .addComponent(lblnc)
                                .addComponent(lbldd))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbltr)
                                .addGap(16, 16, 16)))
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldor)
                            .addComponent(fieldnc)
                            .addComponent(fielddd)
                            .addComponent(fieldtr, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblir)
                            .addComponent(lbls))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fieldir)
                            .addComponent(fields, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnLogout))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnView)
                    .addComponent(btnSend))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblor)
                    .addComponent(fieldor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblir)
                    .addComponent(fieldir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnc)
                    .addComponent(lbls)
                    .addComponent(fieldnc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fields, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldd)
                    .addComponent(fielddd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbltr)
                    .addComponent(fieldtr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "请选择一条记录以发送给客服。", "警告", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 1. 获取选中的 Record ID
        String recordId = (String) jTable1.getValueAt(selectedRow, 0);

        // 2. 查找目标 Customer Service Organization (FrontDeskOrganization)
        Organization targetOrg = findCustomerServiceOrganization();

        if (targetOrg == null) {
             JOptionPane.showMessageDialog(this, "未找到 Customer Service 组织，无法发送请求。", "错误", JOptionPane.ERROR_MESSAGE);
             return;
        }

        // 3. 创建一个新的 Work Request (使用 HealthCareCheckRequest 作为通用请求类型)
        // 实际业务中，可能需要创建一个专门的 CustomerServiceRequest 类
        HealthCareCheckRequest csRequest = new HealthCareCheckRequest();
        csRequest.setMessage("Manager review needed for Record ID: " + recordId);
        csRequest.setSender(account);
        csRequest.setReceiver(null); // 发送到队列
        csRequest.setStatus("Manager Escalate - Pending CS Review");
        csRequest.setBoardingRecordId(recordId); // 关联记录 ID

        // 4. 将请求添加到目标组织的 Work Queue
        targetOrg.getWorkQueue().getWorkRequestList().add(csRequest);

        JOptionPane.showMessageDialog(this, 
            "记录 [" + recordId + "] 已发送给 Customer Service。", 
            "发送成功", JOptionPane.INFORMATION_MESSAGE);

        // 5. 刷新表格（可选）
        // populateTable();
    }//GEN-LAST:event_btnSendActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        // 1. 检查是否选中了表格中的一行
    int selectedRow = jTable1.getSelectedRow();
    if (selectedRow < 0) {
        JOptionPane.showMessageDialog(this, "请先选择一条记录。", "警告", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 2. 获取选中行的 Record ID
    String recordId = (String) jTable1.getValueAt(selectedRow, 0);

    // 3. 根据 Record ID 查找对应的 PetBoardingRecord
    PetBoardingRecord selectedRecord = findRecordById(recordId);

    if (selectedRecord == null) {
        JOptionPane.showMessageDialog(this, "未找到对应的记录。", "错误", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 4. 创建 ManagerViewJPanel 并传递数据
    ManagerViewJPanel viewPanel = new ManagerViewJPanel(
            userProcessContainer, 
            account, 
            organization, 
            enterprise, 
            system
    );

    // 5. 加载记录详情
    viewPanel.loadRecordDetails(selectedRecord);

    // 6. 添加到容器并切换显示
    userProcessContainer.add("ManagerViewJPanel", viewPanel);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.next(userProcessContainer);
}

// ⭐ 辅助方法：根据 Record ID 查找 PetBoardingRecord
private PetBoardingRecord findRecordById(String recordId) {
    if (!(enterprise instanceof PetBoardingEnterprise)) {
        return null;
    }
    
    PetBoardingEnterprise boardingEnt = (PetBoardingEnterprise) enterprise;
    BoardingRecordDirectory recordDirectory = boardingEnt.getBoardingRecordDirectory();
    
    if (recordDirectory != null && recordDirectory.getRecordList() != null) {
        for (PetBoardingRecord record : recordDirectory.getRecordList()) {
            if (record.getRecordId().equals(recordId)) {
                return record;
            }
        }
    }
    return null;
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        java.awt.Component comp = this;

        // 向上遍历组件树，直到找到 MainJFrame
        while (comp != null && !(comp instanceof UI.admin.MainJFrame)) {
            comp = comp.getParent();
        }

        if (comp instanceof UI.admin.MainJFrame) {
            // ⭐ 关键修正：调用新的公共代理方法
            ((UI.admin.MainJFrame) comp).triggerLogout();
        } else {
            // 找不到 MainJFrame，执行后备方案
            if (userProcessContainer != null) {
                userProcessContainer.removeAll();
                userProcessContainer.revalidate();
                userProcessContainer.repaint();
            }
        }
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnView;
    private javax.swing.JTextField fielddd;
    private javax.swing.JTextField fieldir;
    private javax.swing.JTextField fieldnc;
    private javax.swing.JTextField fieldor;
    private javax.swing.JTextField fields;
    private javax.swing.JTextField fieldtr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbldd;
    private javax.swing.JLabel lblir;
    private javax.swing.JLabel lblnc;
    private javax.swing.JLabel lblor;
    private javax.swing.JLabel lbls;
    private javax.swing.JLabel lbltr;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        if (!(enterprise instanceof PetBoardingEnterprise)) {
            return;
        }

        PetBoardingEnterprise boardingEnt = (PetBoardingEnterprise) this.enterprise;
        BoardingRecordDirectory recordDirectory = boardingEnt.getBoardingRecordDirectory();

        // 假设 Manager 关注的是 BoardingServiceOrganization 的 WorkQueue，用于获取健康请求
        // Organization boardingServiceOrg = organization; // 假设传入的 organization 就是 BoardingServiceOrganization

        if (recordDirectory != null && recordDirectory.getRecordList() != null) {
            for (PetBoardingRecord record : recordDirectory.getRecordList()) {
                // 经理通常只看未完成的记录
                if ("Checked In".equals(record.getStatus()) 
                    || "Pending Check-out".equals(record.getStatus())
                    || "Pending Check-in".equals(record.getStatus())) {
                    
                    Pet pet = record.getPet();
                    String notes = record.getNotes();
                    
                    // 1. 查找相关的 HealthCareCheckRequest（如果有的话）
                    HealthCareCheckRequest activeRequest = null;
                    if (organization.getWorkQueue() != null) {
                        for (WorkRequest wr : organization.getWorkQueue().getWorkRequestList()) {
                            if (wr instanceof HealthCareCheckRequest) {
                                HealthCareCheckRequest hcr = (HealthCareCheckRequest) wr;
                                // 假设 Record ID 和 Message 中包含了宠物的身份信息
                                if (hcr.getMessage().contains(pet.getPetName())) {
                                    activeRequest = hcr;
                                    break;
                                }
                            }
                        }
                    }

                    Object[] row = new Object[9];
                    
                    // Record ID, Species
                    row[0] = record.getRecordId();
                    row[1] = (pet != null) ? pet.getSpecies() : "N/A";
                    
                    // ⭐ Daily Care (简化处理：如果 Notes 非空，假设有记录)
                    boolean hasNotes = notes != null && notes.contains("Daily Care Log");
                    String logSymbol = hasNotes ? "✔️" : "---";

                    row[2] = logSymbol; // Breakfast
                    row[3] = logSymbol; // Lunch
                    row[4] = logSymbol; // Dinner
                    row[5] = logSymbol; // Poop
                    row[6] = hasNotes ? "Normal" : "---"; // Mood (简化为 Normal if logged)
                    
                    // Symptom, Message (来自 Health Request)
                    row[7] = (activeRequest != null && activeRequest.getSymptom() != null) ? activeRequest.getSymptom() : "";
                    row[8] = (activeRequest != null) ? activeRequest.getMessage() : "";

                    model.addRow(row);
                }
            }
        }
    }
    
    public void refreshTable() {
        populateTable();
    }
    
    // ⭐ 辅助方法：查找目标 Customer Service Organization (FrontDeskOrganization)
    private Organization findCustomerServiceOrganization() {
    for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
        // 通过类名判断
        if (org instanceof Business.PetBoardingOrganization.CustomerService) {
            return org;
        }
        // 或者通过组织名称判断
        // if (org.getName().contains("Customer Service")) {
        //     return org;
        // }
    }
    return null;
    }

    private void calculateOperationIndicators() {
        if (!(enterprise instanceof PetBoardingEnterprise)) {
            clearOperationFields();
            return;
        }
        PetBoardingEnterprise boardingEnt = (PetBoardingEnterprise) this.enterprise;
        BoardingRecordDirectory recordDirectory = boardingEnt.getBoardingRecordDirectory();
        
        if (recordDirectory == null || recordDirectory.getRecordList() == null) {
            clearOperationFields();
            return;
        }

        // 1. 获取所有记录
        java.util.List<PetBoardingRecord> allRecords = recordDirectory.getRecordList();
        
        // 2. 计算简单指标 (修正 Occupancy Rate)
        // 统计所有处于活动状态的宠物数量 (Checked In 或 Pending Check-out)
        long activelyBoardingCount = allRecords.stream()
            .filter(r -> "Checked In".equals(r.getStatus()) || "Pending Check-out".equals(r.getStatus()))
            .count();
        
        int totalRecords = allRecords.size();
        
        // 假设总房位数是 20
        int totalRooms = 20; 
        
        // --- Occupancy Rate (活动宠物数 / 总房位数) ---
        // 使用 activelyBoardingCount
        double occupancyRateValue = (activelyBoardingCount * 100.0 / totalRooms);
        String occupancyRate = String.format("%.2f%%", occupancyRateValue);
        
        // --- New Check-ins (简化为总记录数) ---
        String newCheckins = String.valueOf(totalRecords); 
        
        // --- Dog/Cat-Days (假设所有宠物都入住 3 天) ---
        String dogCatDays = String.valueOf(totalRecords * 3); 
        
        // --- Incident Rate (假设有健康请求的记录为 Incident) ---
        long incidentCount = organization.getWorkQueue().getWorkRequestList().stream()
            .filter(wr -> wr instanceof HealthCareCheckRequest)
            .count();
        // 分母使用活动宠物数量 (activelyBoardingCount)
        double incidentRateValue = (activelyBoardingCount > 0) ? (incidentCount * 100.0 / activelyBoardingCount) : 0.0;
        String incidentRate = String.format("%.2f%%", incidentRateValue);

        // --- Customer Retention Rate (简化为 N/A) ---
        String retentionRate = "N/A"; 
        
        // --- Total Revenue (简化为每条记录 500 块) ---
        String totalRevenue = "$" + (totalRecords * 500); 

        // --- Staff-to-Dog Ratio (简化为 1:5) ---
        String staffToDogRatio = "1:5"; 

        // 3. 更新字段
        fieldor.setText(occupancyRate);
        fieldnc.setText(newCheckins);
        fielddd.setText(dogCatDays);
        
        fieldtr.setText(totalRevenue);
        fieldir.setText(incidentRate);
        fields.setText(staffToDogRatio);
    }
    
    // ⭐ 新增：清除运营指标字段的方法
    private void clearOperationFields() {
        fieldor.setText("");
        fieldnc.setText("");
        fielddd.setText("");
        
        fieldtr.setText("");
        fieldir.setText("");
        fields.setText("");
    }
        
    }
        
       
    
        

