/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Boarding;

import Business.Enterprise.Enterprise;
import Business.Enterprise.PetBoardingEnterprise;
import Business.Organization.Organization;
import Business.Pet.BoardingRecordDirectory;
import Business.Pet.Pet;
import Business.Pet.PetBoardingRecord;
import Business.Petsystem;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.HealthCareCheckRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import Business.PetBoardingOrganization.CustomerService;

/**
 *
 * @author hanlinyao
 */
public class ManagerJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private UserAccount account;
    private Organization organization;
    private Enterprise enterprise;
    private Petsystem system;

    /**
     * Creates new form ManageJPanel
     */
   public ManagerJPanel(JPanel userProcessContainer, UserAccount account, 
                             Organization organization, Enterprise enterprise, Petsystem system) {
        
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;
        initComponents();
        
        // 初始化表格
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        btnSend = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel1.setText("Welcome to Pet Boarding Manager Work Area");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Record ID", "Species", "Breakfast", "Lunch", "Dinner", "Poop", "Mood", "Symptom", "Message"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnView.setText("View Details");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnSend.setText("Send to Customer service");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(btnView)
                        .addGap(196, 196, 196)
                        .addComponent(btnSend)))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnView)
                    .addComponent(btnSend))
                .addContainerGap(240, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "请选择一条记录以发送给客服。", "警告", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 1. 获取选中的 Record ID
        String recordId = (String) jTable1.getValueAt(selectedRow, 0);

        // 2. 查找目标 Customer Service Organization (FrontDeskOrganization)
        Organization targetOrg = findCustomerServiceOrganization();

        if (targetOrg == null) {
             JOptionPane.showMessageDialog(this, "未找到 Customer Service 组织，无法发送请求。", "错误", JOptionPane.ERROR_MESSAGE);
             return;
        }

        // 3. 创建一个新的 Work Request (使用 HealthCareCheckRequest 作为通用请求类型)
        // 实际业务中，可能需要创建一个专门的 CustomerServiceRequest 类
        HealthCareCheckRequest csRequest = new HealthCareCheckRequest();
        csRequest.setMessage("Manager review needed for Record ID: " + recordId);
        csRequest.setSender(account);
        csRequest.setReceiver(null); // 发送到队列
        csRequest.setStatus("Manager Escalate - Pending CS Review");
        csRequest.setBoardingRecordId(recordId); // 关联记录 ID

        // 4. 将请求添加到目标组织的 Work Queue
        targetOrg.getWorkQueue().getWorkRequestList().add(csRequest);

        JOptionPane.showMessageDialog(this, 
            "记录 [" + recordId + "] 已发送给 Customer Service。", 
            "发送成功", JOptionPane.INFORMATION_MESSAGE);

        // 5. 刷新表格（可选）
        // populateTable();
    }//GEN-LAST:event_btnSendActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        // 1. 检查是否选中了表格中的一行
    int selectedRow = jTable1.getSelectedRow();
    if (selectedRow < 0) {
        JOptionPane.showMessageDialog(this, "请先选择一条记录。", "警告", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 2. 获取选中行的 Record ID
    String recordId = (String) jTable1.getValueAt(selectedRow, 0);

    // 3. 根据 Record ID 查找对应的 PetBoardingRecord
    PetBoardingRecord selectedRecord = findRecordById(recordId);

    if (selectedRecord == null) {
        JOptionPane.showMessageDialog(this, "未找到对应的记录。", "错误", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 4. 创建 ManagerViewJPanel 并传递数据
    ManagerViewJPanel viewPanel = new ManagerViewJPanel(
            userProcessContainer, 
            account, 
            organization, 
            enterprise, 
            system
    );

    // 5. 加载记录详情
    viewPanel.loadRecordDetails(selectedRecord);

    // 6. 添加到容器并切换显示
    userProcessContainer.add("ManagerViewJPanel", viewPanel);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.next(userProcessContainer);
}

// ⭐ 辅助方法：根据 Record ID 查找 PetBoardingRecord
private PetBoardingRecord findRecordById(String recordId) {
    if (!(enterprise instanceof PetBoardingEnterprise)) {
        return null;
    }
    
    PetBoardingEnterprise boardingEnt = (PetBoardingEnterprise) enterprise;
    BoardingRecordDirectory recordDirectory = boardingEnt.getBoardingRecordDirectory();
    
    if (recordDirectory != null && recordDirectory.getRecordList() != null) {
        for (PetBoardingRecord record : recordDirectory.getRecordList()) {
            if (record.getRecordId().equals(recordId)) {
                return record;
            }
        }
    }
    return null;
    }//GEN-LAST:event_btnViewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        if (!(enterprise instanceof PetBoardingEnterprise)) {
            return;
        }

        PetBoardingEnterprise boardingEnt = (PetBoardingEnterprise) this.enterprise;
        BoardingRecordDirectory recordDirectory = boardingEnt.getBoardingRecordDirectory();

        // 假设 Manager 关注的是 BoardingServiceOrganization 的 WorkQueue，用于获取健康请求
        // Organization boardingServiceOrg = organization; // 假设传入的 organization 就是 BoardingServiceOrganization

        if (recordDirectory != null && recordDirectory.getRecordList() != null) {
            for (PetBoardingRecord record : recordDirectory.getRecordList()) {
                // 经理通常只看未完成的记录
                if ("Checked In".equals(record.getStatus()) || "Pending Check-out".equals(record.getStatus())) {
                    
                    Pet pet = record.getPet();
                    String notes = record.getNotes();
                    
                    // 1. 查找相关的 HealthCareCheckRequest（如果有的话）
                    HealthCareCheckRequest activeRequest = null;
                    if (organization.getWorkQueue() != null) {
                        for (WorkRequest wr : organization.getWorkQueue().getWorkRequestList()) {
                            if (wr instanceof HealthCareCheckRequest) {
                                HealthCareCheckRequest hcr = (HealthCareCheckRequest) wr;
                                // 假设 Record ID 和 Message 中包含了宠物的身份信息
                                if (hcr.getMessage().contains(pet.getPetName())) {
                                    activeRequest = hcr;
                                    break;
                                }
                            }
                        }
                    }

                    Object[] row = new Object[9];
                    
                    // Record ID, Species
                    row[0] = record.getRecordId();
                    row[1] = (pet != null) ? pet.getSpecies() : "N/A";
                    
                    // ⭐ Daily Care (简化处理：如果 Notes 非空，假设有记录)
                    boolean hasNotes = notes != null && notes.contains("Daily Care Log");
                    String logSymbol = hasNotes ? "✔️" : "---";

                    row[2] = logSymbol; // Breakfast
                    row[3] = logSymbol; // Lunch
                    row[4] = logSymbol; // Dinner
                    row[5] = logSymbol; // Poop
                    row[6] = hasNotes ? "Normal" : "---"; // Mood (简化为 Normal if logged)
                    
                    // Symptom, Message (来自 Health Request)
                    row[7] = (activeRequest != null && activeRequest.getSymptom() != null) ? activeRequest.getSymptom() : "";
                    row[8] = (activeRequest != null) ? activeRequest.getMessage() : "";

                    model.addRow(row);
                }
            }
        }
    }
    
    public void refreshTable() {
        populateTable();
    }
    
    // ⭐ 辅助方法：查找目标 Customer Service Organization (FrontDeskOrganization)
    private Organization findCustomerServiceOrganization() {
    for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
        // 通过类名判断
        if (org instanceof Business.PetBoardingOrganization.CustomerService) {
            return org;
        }
        // 或者通过组织名称判断
        // if (org.getName().contains("Customer Service")) {
        //     return org;
        // }
    }
    return null;
    }
       
    }
        

