/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Boarding;

import Business.Enterprise.Enterprise;
import Business.Enterprise.PetBoardingEnterprise;
import Business.Organization.Organization;
import Business.Pet.BoardingRecordDirectory;
import Business.Pet.Pet;
import Business.Pet.PetBoardingRecord;
import Business.Petsystem;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.HealthCareCheckRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import Business.PetBoardingOrganization.CustomerService;
import java.text.SimpleDateFormat;

/**
 *
 * @author hanlinyao
 */
public class ManagerJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private UserAccount account;
    private Organization organization;
    private Enterprise enterprise;
    private Petsystem system;
    
    private final SimpleDateFormat FULL_DATE_FORMAT = new SimpleDateFormat("EEE MMM dd HH:mm:ss zzz yyyy");
    private final SimpleDateFormat YEAR_DATE_FORMAT = new SimpleDateFormat("yyyy");

    /**
     * Creates new form ManageJPanel
     */
   public ManagerJPanel(JPanel userProcessContainer, UserAccount account, 
                             Organization organization, Enterprise enterprise, Petsystem system) {
        
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;
        initComponents();
        
        // 初始化表格
        populateTable();
         
       
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnView = new javax.swing.JButton();
        btnSend = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Welcome to Pet Boarding Manager Work Area");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Record ID", "Species", "Breakfast", "Lunch", "Dinner", "Poop", "Mood", "Symptom", "Message"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnView.setText("View Details");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnSend.setText("Send to Customer service");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogout)))
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(btnView)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSend)
                .addGap(173, 173, 173))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnLogout))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSend)
                    .addComponent(btnView))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(257, 257, 257))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a record to send to the customer service.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 1. 获取选中的 Record ID
        String recordId = (String) jTable1.getValueAt(selectedRow, 0);
            PetBoardingRecord selectedRecord = findRecordById(recordId);
        Pet pet = (selectedRecord != null) ? selectedRecord.getPet() : null;

        if (pet == null) {
            JOptionPane.showMessageDialog(this, "Error: Unable to find the relevant pet information based on the record ID.", "Warning", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 2. 查找目标 Customer Service Organization (FrontDeskOrganization)
        Organization targetOrg = findCustomerServiceOrganization();

        if (targetOrg == null) {
             JOptionPane.showMessageDialog(this, "The \"Customer Service\" organization was not found, so the request could not be sent.", "warning", JOptionPane.ERROR_MESSAGE);
             return;
        }
        for (WorkRequest wr : targetOrg.getWorkQueue().getWorkRequestList()) {
        if (wr instanceof HealthCareCheckRequest) {
            HealthCareCheckRequest existing = (HealthCareCheckRequest) wr;
            if (recordId.equals(existing.getBoardingRecordId())) {
                JOptionPane.showMessageDialog(this, 
                    "Record [" + recordId + "] has already been sent to Customer Service.", 
                    "Info", JOptionPane.INFORMATION_MESSAGE);
                return;  // 已存在，直接返回
            }
        }
    }
        // ⭐⭐ 步骤 2：查找与该记录相关的 HealthCareCheckRequest，以获取 Symptom
    HealthCareCheckRequest sourceRequest = null;
    if (organization.getWorkQueue() != null) {
        for (WorkRequest wr : organization.getWorkQueue().getWorkRequestList()) {
            if (wr instanceof HealthCareCheckRequest) {
                HealthCareCheckRequest hcr = (HealthCareCheckRequest) wr;
                // 使用我们之前修复的 BoardingRecordId 精确匹配
                if (recordId.equals(hcr.getBoardingRecordId())) { 
                    sourceRequest = hcr;
                    break;
                }
            }
        }
    }

        // 3. 创建一个新的 Work Request (使用 HealthCareCheckRequest 作为通用请求类型)
        // 实际业务中，可能需要创建一个专门的 CustomerServiceRequest 类
        HealthCareCheckRequest csRequest = new HealthCareCheckRequest();
        csRequest.setMessage("Manager review needed for Record ID: " + recordId);
        csRequest.setSender(account);
        csRequest.setReceiver(null); // 发送到队列
        csRequest.setStatus("Manager Escalate - Pending CS Review");
        csRequest.setBoardingRecordId(recordId); // 关联记录 ID
        csRequest.setPet(pet);
        // ⭐⭐⭐ 核心修复：设置 Symptom 字段
    if (sourceRequest != null) {
        // 从原始请求中继承症状
        csRequest.setSymptom(sourceRequest.getSymptom());
    } else {
        // 如果找不到原始请求，可以提示 Manager 输入
        String newSymptom = JOptionPane.showInputDialog(this, "Please enter the symptoms that you would like to report to the customer service:", "Manager update request", JOptionPane.QUESTION_MESSAGE);
        if (newSymptom == null || newSymptom.trim().isEmpty()) {
             newSymptom = "Manager Escalation - No specific symptom recorded.";
        }
        csRequest.setSymptom(newSymptom);
    }
        // 4. 将请求添加到目标组织的 Work Queue
        targetOrg.getWorkQueue().getWorkRequestList().add(csRequest);

        JOptionPane.showMessageDialog(this, 
            "record [" + recordId + "] send to Customer Service。", 
            "Success", JOptionPane.INFORMATION_MESSAGE);

        // 5. 刷新表格（可选）
         populateTable();
    }//GEN-LAST:event_btnSendActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        // 1. 检查是否选中了表格中的一行
    int selectedRow = jTable1.getSelectedRow();
    if (selectedRow < 0) {
        JOptionPane.showMessageDialog(this, "Please choice one record", "warning", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 2. 获取选中行的 Record ID
    String recordId = (String) jTable1.getValueAt(selectedRow, 0);

    // 3. 根据 Record ID 查找对应的 PetBoardingRecord
    PetBoardingRecord selectedRecord = findRecordById(recordId);

    if (selectedRecord == null) {
        JOptionPane.showMessageDialog(this, "No corresponding record was found.", "warning", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // 4. 创建 ManagerViewJPanel 并传递数据
    ManagerViewJPanel viewPanel = new ManagerViewJPanel(
            userProcessContainer, 
            account, 
            organization, 
            enterprise, 
            system
    );

    // 5. 加载记录详情
    viewPanel.loadRecordDetails(selectedRecord);

    // 6. 添加到容器并切换显示
    userProcessContainer.add("ManagerViewJPanel", viewPanel);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.next(userProcessContainer);
}

// ⭐ 辅助方法：根据 Record ID 查找 PetBoardingRecord
private PetBoardingRecord findRecordById(String recordId) {
    System.out.println("=== DEBUG findRecordById ===");
    System.out.println("Looking for BoardingRecord with ID: " + recordId);
    System.out.println("System: " + system);
    
    if (system == null) {
        System.out.println("❌ System is NULL!");
        return null;
    }
    
    // 遍历所有 Network
    if (system.getNetworkList() != null) {
        System.out.println("Network count: " + system.getNetworkList().size());
        
        for (Business.Network.Network network : system.getNetworkList()) {
            System.out.println("  Network: " + network.getName());
            
            // 遍历该 Network 中的所有 Enterprise
            if (network.getEnterpriseDirectory() != null) {
                for (Enterprise ent : network.getEnterpriseDirectory().getEnterpriseList()) {
                    System.out.println("    Enterprise: " + ent.getName() + " [" + ent.getClass().getSimpleName() + "]");
                    
                    // 只处理 PetBoardingEnterprise
                    if (ent instanceof PetBoardingEnterprise) {
                        PetBoardingEnterprise boardingEnt = (PetBoardingEnterprise) ent;
                        BoardingRecordDirectory recordDirectory = boardingEnt.getBoardingRecordDirectory();
                        
                        if (recordDirectory != null && recordDirectory.getRecordList() != null) {
                            System.out.println("    Total records: " + recordDirectory.getRecordList().size());
                            
                            for (PetBoardingRecord record : recordDirectory.getRecordList()) {
                                System.out.println("      - Record ID: " + record.getRecordId());
                                
                                if (record.getRecordId().equals(recordId)) {
                                    System.out.println("    ✅ Found record: " + recordId);
                                    return record;
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    
    System.out.println("❌ Record not found: " + recordId);
    return null;

    }//GEN-LAST:event_btnViewActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        java.awt.Component comp = this;

        // 向上遍历组件树，直到找到 MainJFrame
        while (comp != null && !(comp instanceof UI.admin.MainJFrame)) {
            comp = comp.getParent();
        }

        if (comp instanceof UI.admin.MainJFrame) {
            // ⭐ 关键修正：调用新的公共代理方法
            ((UI.admin.MainJFrame) comp).triggerLogout();
        } else {
            // 找不到 MainJFrame，执行后备方案
            if (userProcessContainer != null) {
                userProcessContainer.removeAll();
                userProcessContainer.revalidate();
                userProcessContainer.repaint();
            }
        }
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        if (!(enterprise instanceof PetBoardingEnterprise)) {
            return;
        }

        PetBoardingEnterprise boardingEnt = (PetBoardingEnterprise) this.enterprise;
        BoardingRecordDirectory recordDirectory = boardingEnt.getBoardingRecordDirectory();

        // 假设 Manager 关注的是 BoardingServiceOrganization 的 WorkQueue，用于获取健康请求
        // Organization boardingServiceOrg = organization; // 假设传入的 organization 就是 BoardingServiceOrganization

        if (recordDirectory != null && recordDirectory.getRecordList() != null) {
            for (PetBoardingRecord record : recordDirectory.getRecordList()) {
                // 经理通常只看未完成的记录
                if ("Checked In".equals(record.getStatus()) 
                    || "Pending Check-out".equals(record.getStatus())
                    || "Pending Check-in".equals(record.getStatus())) {
                    
                    Pet pet = record.getPet();
                    String notes = record.getNotes();
                    
                    // 1. 查找相关的 HealthCareCheckRequest（如果有的话）
                HealthCareCheckRequest activeRequest = null;
                if (organization.getWorkQueue() != null) {
                    for (WorkRequest wr : organization.getWorkQueue().getWorkRequestList()) {
                        if (wr instanceof HealthCareCheckRequest) {
                            HealthCareCheckRequest hcr = (HealthCareCheckRequest) wr;
                            
                            // 🌟 修复后的核心逻辑：使用 BoardingRecordId 精确匹配
                            if (record.getRecordId().equals(hcr.getBoardingRecordId())) {
                                activeRequest = hcr;
                                break;
                            }
                        }
                    }
                }

                    Object[] row = new Object[9];
                    
                    // Record ID, Species
                    row[0] = record.getRecordId();
                    row[1] = (pet != null) ? pet.getSpecies() : "N/A";
                    
                    // ⭐ Daily Care (简化处理：如果 Notes 非空，假设有记录)
                    boolean hasNotes = notes != null && notes.contains("Daily Care Log");
                    String logSymbol = hasNotes ? "✔️" : "---";

                    row[2] = logSymbol; // Breakfast
                    row[3] = logSymbol; // Lunch
                    row[4] = logSymbol; // Dinner
                    row[5] = logSymbol; // Poop
                    row[6] = hasNotes ? "Normal" : "---"; // Mood (简化为 Normal if logged)
                    
                    // Symptom, Message (来自 Health Request)
                    row[7] = (activeRequest != null && activeRequest.getSymptom() != null) ? activeRequest.getSymptom() : "";
                    row[8] = (activeRequest != null) ? activeRequest.getMessage() : "";

                    model.addRow(row);
                }
            }
        }
    }
    
    public void refreshTable() {
        populateTable();
    }
    
    // ⭐ 辅助方法：查找目标 Customer Service Organization (FrontDeskOrganization)
    private Organization findCustomerServiceOrganization() {
    for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
        // 通过类名判断
        if (org instanceof Business.PetBoardingOrganization.CustomerService) {
            return org;
        }
        // 或者通过组织名称判断
        // if (org.getName().contains("Customer Service")) {
        //     return org;
        // }
    }
    return null;
    }

   
    
    
        
    }
        
       
    
        

