/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Boarding;
import Business.Enterprise.Enterprise;
import Business.Enterprise.PetBoardingEnterprise;
import Business.Pet.BoardingRecordDirectory;
import Business.Pet.Pet;
import Business.Pet.PetBoardingRecord;
import Business.Pet.PetOwner;
import Business.PetBoardingOrganization.BoardingServiceOrganization;
import Business.Petsystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hanlinyao
 */
public class RecordJPanel extends javax.swing.JPanel {
     private JPanel userProcessContainer;
    private UserAccount account;
    private BoardingServiceOrganization organization;
    private Enterprise enterprise;
    private Petsystem system;

    /**
     * Creates new form RecordJPanel
     */
    public RecordJPanel(JPanel userProcessContainer, UserAccount account, 
                         BoardingServiceOrganization organization, 
                         Enterprise enterprise, Petsystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;
        
        // 初始加载表格数据
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTittle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRecord = new javax.swing.JTable();
        lblBreakfast = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        lblLunch = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        lblDinner = new javax.swing.JLabel();
        jCheckBox3 = new javax.swing.JCheckBox();
        lblPoop = new javax.swing.JLabel();
        jCheckBox4 = new javax.swing.JCheckBox();
        lblMood = new javax.swing.JLabel();
        combMood = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        btnBack = new javax.swing.JButton();

        lblTittle.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblTittle.setText("Record Today's Care");

        tblRecord.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Record ID", "Message", "Symptom", "Pet Name", "Record Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRecord);

        lblBreakfast.setText("Breakfast");

        jCheckBox1.setText("Yes");

        lblLunch.setText("Lunch");

        jCheckBox2.setText("Yes");

        lblDinner.setText("Dinner");

        jCheckBox3.setText("Yes");

        lblPoop.setText("Poop");

        jCheckBox4.setText("Yes");

        lblMood.setText("Mood");

        combMood.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Excited", "Normal", "Frustrated" }));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jCheckBox5.setText("No");

        jCheckBox6.setText("No");

        jCheckBox7.setText("No");

        jCheckBox8.setText("No");

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDinner, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox8))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblBreakfast, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jCheckBox1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jCheckBox5))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblLunch, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jCheckBox2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jCheckBox6)))
                                        .addGap(141, 141, 141)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(lblPoop, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jCheckBox4))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblMood, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(combMood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox7))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)
                        .addGap(152, 152, 152)
                        .addComponent(lblTittle, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(btnSave)))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTittle)
                    .addComponent(btnBack))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBreakfast)
                            .addComponent(jCheckBox1)
                            .addComponent(jCheckBox5))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox2)
                            .addComponent(jCheckBox6)
                            .addComponent(lblLunch)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPoop)
                            .addComponent(jCheckBox4)
                            .addComponent(jCheckBox7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMood)
                            .addComponent(combMood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox8)
                    .addComponent(lblDinner))
                .addGap(26, 26, 26)
                .addComponent(btnSave)
                .addGap(0, 241, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        
        Component[] componentArray = userProcessContainer.getComponents();
        if (componentArray.length > 0) {
            Component component = componentArray[componentArray.length - 1];
            if (component instanceof WelcomJpanel) {
                WelcomJpanel welcomePanel = (WelcomJpanel) component;
                welcomePanel.refreshTable();
            }
        }
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblRecord.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please first select a foster care record from the table.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // 1. 读取数据
        String recordId = (String) tblRecord.getValueAt(selectedRow, 0);
        
        boolean hadBreakfast = jCheckBox1.isSelected();
        boolean hadLunch = jCheckBox2.isSelected();
        boolean hadDinner = jCheckBox3.isSelected();
        boolean hadPoop = jCheckBox4.isSelected();
        String mood = (String) combMood.getSelectedItem();
        
        // 2. 模拟保存逻辑（在实际系统中，这会更新到 PetBoardingRecord 或 DailyCareLog 中）
        String careDetails = String.format(
            "--- Daily Care Log (%s) ---\n" +
            "Breakfast: %s, Lunch: %s, Dinner: %s, Defecation: %s, Mood: %s",
            new SimpleDateFormat("yyyy-MM-dd").format(new Date()),
            hadBreakfast ? "Is" : "Is not",
            hadLunch ? "Is" : "Is not",
            hadDinner ? "Is" : "Is not",
            hadPoop ? "Is" : "Is not",
            mood
        );
        
        // 查找记录对象，并更新 Notes（作为临时的每日日志存储）
        PetBoardingEnterprise boardingEnt = (PetBoardingEnterprise) this.enterprise;
        BoardingRecordDirectory recordDirectory = boardingEnt.getBoardingRecordDirectory();
        PetBoardingRecord record = recordDirectory.findRecordById(recordId); 
        
        if (record != null) {
            String existingNotes = record.getNotes();
            record.setNotes(existingNotes + "\n" + careDetails); // 附加到现有 Notes
        }
        
        // 3. 提示并清理 UI
        JOptionPane.showMessageDialog(this, 
           "Daily care records for [" + recordId + "] have been successfully saved!\nEmotion: " + mood, 
            "success", JOptionPane.INFORMATION_MESSAGE);
        
        // 清理 CheckBoxes 和 ComboBox
        jCheckBox1.setSelected(false);
        jCheckBox2.setSelected(false);
        jCheckBox3.setSelected(false);
        jCheckBox4.setSelected(false);
        jCheckBox5.setSelected(false);
        jCheckBox6.setSelected(false);
        jCheckBox7.setSelected(false);
        jCheckBox8.setSelected(false);
        combMood.setSelectedIndex(1); // 设置回 Normal
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> combMood;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBreakfast;
    private javax.swing.JLabel lblDinner;
    private javax.swing.JLabel lblLunch;
    private javax.swing.JLabel lblMood;
    private javax.swing.JLabel lblPoop;
    private javax.swing.JLabel lblTittle;
    private javax.swing.JTable tblRecord;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblRecord.getModel();
        model.setRowCount(0);
        
        if (!(enterprise instanceof PetBoardingEnterprise)) {
            return;
        }

        PetBoardingEnterprise boardingEnt = (PetBoardingEnterprise) this.enterprise;
        BoardingRecordDirectory recordDirectory = boardingEnt.getBoardingRecordDirectory();

        try {
            if (recordDirectory != null && recordDirectory.getRecordList() != null) {
                // 仅显示状态为 "Checked In" 或 "Pending Check-out" 的记录
                for (PetBoardingRecord record : recordDirectory.getRecordList()) {
                    if (!"Completed".equalsIgnoreCase(record.getStatus())) {
                        Object[] row = new Object[5];
                        Pet pet = record.getPet();

                        row[0] = record.getRecordId(); // Record ID
                        row[1] = (pet != null) ? pet.getPetName() : "N/A"; // Pet Name
                        row[2] = record.getRoomNumber(); // Room Number
                        row[3] = record.getStatus(); // Status
                        row[4] = record.getEndDate(); // End Date
                        
                        model.addRow(row);
                    }
                }
            }
        } catch (Exception e) {
             JOptionPane.showMessageDialog(this, "An error occurred while loading the record table.: " + e.getMessage(), "数据加载错误", JOptionPane.ERROR_MESSAGE);
        }
    }
        
}
