/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Boarding;
import Business.Enterprise.Enterprise;
import Business.Enterprise.PetBoardingEnterprise;
import Business.Pet.Pet;
import Business.Pet.PetBoardingRecord;
import Business.Pet.PetOwner;
import Business.PetBoardingOrganization.BoardingServiceOrganization;
import Business.Petsystem;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.HealthCareCheckRequest; // 导入 HealthCareCheckRequest
import Business.WorkQueue.WorkRequest; // 导入 WorkRequest
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import java.util.Random; // 用于生成 Pet ID 供演示
import Business.Network.Network;
import Business.Organization.Organization;
import Business.PetClinicOrganization.FrontDeskOrganization;
import Business.Role.FrontDeskAgentRole;
import Business.Enterprise.PetClinicEnterprise;


/**
 *
 * @author hanlinyao
 */
public class SubmitJPanel extends javax.swing.JPanel {
     private JPanel userProcessContainer;
    private UserAccount account;
    private BoardingServiceOrganization organization;
    private Enterprise enterprise;
    private Petsystem system;

    /**
     * Creates new form SubmitJPanel
     */
    public SubmitJPanel(JPanel userProcessContainer, UserAccount account, 
                         BoardingServiceOrganization organization, 
                         Enterprise enterprise, Petsystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;
        
        // 初始加载表格数据
        populateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTaker = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTitle.setText("Pet Caretaker");

        tblTaker.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Record ID", "Symptom", "Message", "Sender", "Receiver", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTaker);

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnBack.setText("<<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(469, 469, 469)
                        .addComponent(btnBack))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(lblTitle))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(btnAdd)
                .addContainerGap(261, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
         userProcessContainer.remove(this);
        
        Component[] componentArray = userProcessContainer.getComponents();
        if (componentArray.length > 0) {
            Component component = componentArray[componentArray.length - 1];
            if (component instanceof WelcomJpanel) {
                WelcomJpanel welcomePanel = (WelcomJpanel) component;
                welcomePanel.refreshTable();
            }
        }
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
     // 1. 获取 Boarding Record ID (必须)
    String recordId = JOptionPane.showInputDialog(this, 
        "Please enter the related Boarding Record ID:", 
        "Submit request", JOptionPane.QUESTION_MESSAGE);

    if (recordId == null || recordId.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, 
            "Boarding Record ID is required.", 
            "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // ⭐⭐⭐ 新增：根据 recordId 查找 PetBoardingRecord 并获取 Pet ⭐⭐⭐
    PetBoardingRecord boardingRecord = findBoardingRecordById(recordId.trim());
    
    if (boardingRecord == null) {
        JOptionPane.showMessageDialog(this, 
            "Boarding Record ID [" + recordId + "] not found.\nPlease check and try again.", 
            "Record Not Found", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    Pet pet = boardingRecord.getPet();
    if (pet == null) {
        JOptionPane.showMessageDialog(this, 
            "No pet associated with this boarding record.", 
            "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

        // 2. 获取 Symptom (症状) (必须)
        String symptom = JOptionPane.showInputDialog(this, "Please enter the pet's main symptom:", "Submit request", JOptionPane.QUESTION_MESSAGE);

        if (symptom == null || symptom.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Symptom is required.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // 3. 获取 Message (附注信息) (可选)
        String notes = JOptionPane.showInputDialog(this, "Please provide any additional notes:", "Submit request", JOptionPane.QUESTION_MESSAGE);
        
        // 4. 构造最终的 message
        String finalMessage;
        if (notes == null || notes.trim().isEmpty()) {
            finalMessage = "Symptom observed: " + symptom;
        } else {
            finalMessage = "Symptom: " + symptom + ". Notes: " + notes;
        }

        // 5. 创建 Work Request
    HealthCareCheckRequest request = new HealthCareCheckRequest();
    request.setMessage(finalMessage); 
    request.setSymptom(symptom);      
    request.setSender(account);
    request.setBoardingRecordId(recordId); 
     request.setPet(pet);

        // 6. 查找目标 Clinic 组织
    Organization targetOrganization = findTargetFrontDeskOrganization();
    
    if (targetOrganization != null) {
        request.setReceiver(null); 
        request.setStatus("Sent to Clinic Queue"); 
        
        // ⭐ 修改：将请求添加到目标组织的队列
        targetOrganization.getWorkQueue().getWorkRequestList().add(request);
        
        // ⭐ 新增：同时将请求添加到当前组织的队列（这样本页面表格能显示）
        organization.getWorkQueue().getWorkRequestList().add(request);

        JOptionPane.showMessageDialog(this, 
            "The health check request for Record ID [" + recordId + "] has been submitted.", 
            "Request Sent", JOptionPane.INFORMATION_MESSAGE);
        
    } else {
        JOptionPane.showMessageDialog(this, 
            "Error: Could not find a Pet Clinic Front Desk Organization.", 
            "System Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
        
        // 7. 刷新表格
    populateTable();
}

// ⭐⭐⭐ 新增辅助方法：根据 recordId 查找 PetBoardingRecord ⭐⭐⭐
private PetBoardingRecord findBoardingRecordById(String recordId) {
    // 方法1：从当前 enterprise 获取（如果 enterprise 是 PetBoardingEnterprise）
    if (enterprise instanceof PetBoardingEnterprise) {
        PetBoardingEnterprise boardingEnterprise = (PetBoardingEnterprise) enterprise;
        PetBoardingRecord record = boardingEnterprise.getBoardingRecordDirectory().findRecordById(recordId);
        if (record != null) {
            return record;
        }
    }
    
    // 方法2：遍历所有网络中的 PetBoardingEnterprise 查找
    for (Network network : system.getNetworkList()) {
        for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
            if (e instanceof PetBoardingEnterprise) {
                PetBoardingEnterprise boardingEnt = (PetBoardingEnterprise) e;
                PetBoardingRecord record = boardingEnt.getBoardingRecordDirectory().findRecordById(recordId);
                if (record != null) {
                    return record;
                }
            }
        }
    }
    
    return null;

        
        
    
    
    }//GEN-LAST:event_btnAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblTaker;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
     DefaultTableModel model = (DefaultTableModel) tblTaker.getModel();
        model.setRowCount(0);
        
        if (organization == null || organization.getWorkQueue() == null) {
            return;
        }
        
        // 预先查找目标组织的名称，用于显示
        Organization targetOrg = findTargetFrontDeskOrganization();
        String targetOrgName = (targetOrg != null) ? targetOrg.getName() + " Queue" : "N/A";


        // 遍历当前组织的工作请求队列
        for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()) {
            // 仅显示 HealthCareCheckRequest
            if (request instanceof HealthCareCheckRequest) {
                HealthCareCheckRequest healthRequest = (HealthCareCheckRequest) request;
                
                // 6 列数据
                Object[] row = new Object[6]; 
                
                // 填充数据
                row[0] = healthRequest.getBoardingRecordId() != null ? healthRequest.getBoardingRecordId() : "N/A"; 
                row[1] = healthRequest.getSymptom() != null ? healthRequest.getSymptom() : "N/A"; 
                row[2] = healthRequest.getMessage();
                // Sender (显示 Employee Name)
                row[3] = healthRequest.getSender() != null ? healthRequest.getSender().getEmployee().getName() : "N/A";
                // ⭐ Receiver (如果为 null，显示目标组织名称/队列)
                row[4] = healthRequest.getReceiver() != null ? healthRequest.getReceiver().getEmployee().getName() : targetOrgName; 
                row[5] = healthRequest.getStatus();
                
                model.addRow(row);
            }
        }
        }
 
    // ⭐ 辅助方法：查找目标 Clinic Front Desk Organization
    private Organization findTargetFrontDeskOrganization() {
        // 遍历整个系统来找到第一个 Pet Clinic 的 FrontDeskOrganization
        for (Network network : system.getNetworkList()) {
            for (Enterprise e : network.getEnterpriseDirectory().getEnterpriseList()) {
                // 找到宠物诊所企业
                if (e.getEnterpriseType() == Enterprise.EnterpriseType.PetClinic) {
                    for (Organization org : e.getOrganizationDirectory().getOrganizationList()) {
                        // 找到前台组织
                        if (org instanceof FrontDeskOrganization) {
                            return org;
                        }
                    }
                }
            }
        }
        return null;
    }
    }
       

