/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Boarding;
import Business.Enterprise.Enterprise;
import Business.Pet.Pet;
import Business.Pet.PetBoardingRecord;
import Business.Pet.PetOwner;
import Business.PetBoardingOrganization.BoardingServiceOrganization;
import Business.Petsystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author hanlinyao
 */
public class ViewJPanel extends javax.swing.JPanel {
     private JPanel userProcessContainer;
    private UserAccount account;
    private BoardingServiceOrganization organization;
    private Enterprise enterprise;
    private Petsystem system;
    // ⭐ 新增：用于存储当前正在查看/编辑的记录
    private PetBoardingRecord selectedRecord;

    /**
     * Creates new form ViewJPanel
     */
    public ViewJPanel(JPanel userProcessContainer, UserAccount account, 
                         BoardingServiceOrganization organization, 
                         Enterprise enterprise, Petsystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;
        
        // 初始化时禁用编辑模式
        setFieldsEditable(false);
        // 隐藏 Save 按钮，只有点击 Modify 后才显示
        btnSave.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldWeight = new javax.swing.JTextField();
        lblAge = new javax.swing.JLabel();
        lblWeight = new javax.swing.JLabel();
        fieldOwnerName = new javax.swing.JTextField();
        fieldPhone = new javax.swing.JTextField();
        fieldAddress = new javax.swing.JTextField();
        lblBoarding = new javax.swing.JLabel();
        fieldEmail = new javax.swing.JTextField();
        lblRoom = new javax.swing.JLabel();
        lblSD = new javax.swing.JLabel();
        fieldCompany = new javax.swing.JTextField();
        lblED = new javax.swing.JLabel();
        fieldPolicy = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        fieldCL = new javax.swing.JTextField();
        fieldRoom = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        fieldSD = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        fieldED = new javax.swing.JTextField();
        btnModifty = new javax.swing.JButton();
        lblInsurance = new javax.swing.JLabel();
        lblEp = new javax.swing.JLabel();
        lblCompany = new javax.swing.JLabel();
        fieldEp = new javax.swing.JTextField();
        lblPolicy = new javax.swing.JLabel();
        lblFood = new javax.swing.JLabel();
        lblCoverage = new javax.swing.JLabel();
        fieldFood = new javax.swing.JTextField();
        lblTitle = new javax.swing.JLabel();
        fieldPetName = new javax.swing.JTextField();
        lblPet = new javax.swing.JLabel();
        fieldSpecies = new javax.swing.JTextField();
        fieldAge = new javax.swing.JTextField();
        lblPetName = new javax.swing.JLabel();
        lblSpecies = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblPetowner = new javax.swing.JLabel();
        lblContact = new javax.swing.JLabel();
        fieldContact = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 204));

        fieldWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldWeightActionPerformed(evt);
            }
        });

        lblAge.setText("Age");

        lblWeight.setText("Weight");

        fieldAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldAddressActionPerformed(evt);
            }
        });

        lblBoarding.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblBoarding.setForeground(new java.awt.Color(0, 51, 255));
        lblBoarding.setText("Boarding");

        lblRoom.setText("Room Number");

        lblSD.setText("Start Date");

        lblED.setText("End Date");

        lblName.setText("Name");

        lblPhone.setText("Phone No");

        lblAddress.setText("Address");

        lblEmail.setText("Email");

        btnModifty.setText("Modifty");
        btnModifty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModiftyActionPerformed(evt);
            }
        });

        lblInsurance.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblInsurance.setForeground(new java.awt.Color(0, 102, 255));
        lblInsurance.setText("Insurance");

        lblEp.setText("Expiration Date");

        lblCompany.setText("Insurance Company");

        lblPolicy.setText("Policy No");

        lblFood.setText("Food Allergy");

        lblCoverage.setText("Coverage Level");

        fieldFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldFoodActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblTitle.setText("View Details");

        lblPet.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblPet.setForeground(new java.awt.Color(0, 51, 255));
        lblPet.setText("Pet");

        lblPetName.setText("Pet Name");

        lblSpecies.setText("Species");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnBack.setText("<<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblPetowner.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblPetowner.setForeground(new java.awt.Color(0, 51, 255));
        lblPetowner.setText("Pet Owner");

        lblContact.setText("Emergency Contact");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(lblBoarding)
                        .addGap(259, 259, 259)
                        .addComponent(lblInsurance))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(358, 358, 358)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPolicy)
                            .addComponent(lblCoverage)
                            .addComponent(lblEp))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblSpecies)
                            .addComponent(lblPetName)
                            .addComponent(lblAge)
                            .addComponent(lblWeight))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldSpecies, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldPetName, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(fieldFood, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblPet)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(lblFood))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblRoom)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblED)
                                .addComponent(lblSD)))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fieldRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldSD, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldED, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCompany)
                                .addGap(18, 18, 18)
                                .addComponent(fieldCompany))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldCL)
                                    .addComponent(fieldEp)
                                    .addComponent(fieldPolicy)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPhone)
                                    .addComponent(lblName))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fieldOwnerName)
                                    .addComponent(fieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblContact)
                                    .addComponent(lblAddress)
                                    .addComponent(lblEmail))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(fieldContact, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblPetowner)
                                .addGap(105, 105, 105))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnModifty)
                                .addGap(39, 39, 39)
                                .addComponent(btnSave)
                                .addGap(157, 157, 157)))))
                .addGap(124, 124, 124))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle)
                    .addComponent(btnBack))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(269, 269, 269)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBoarding)
                            .addComponent(lblInsurance)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblPetowner)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblName)
                                .addComponent(fieldOwnerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblPhone)
                                .addComponent(fieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblAddress)
                                .addComponent(fieldAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblEmail)
                                .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblContact)
                                .addComponent(fieldContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblPet)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblPetName)
                                .addComponent(fieldPetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblSpecies)
                                .addComponent(fieldSpecies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblAge)
                                .addComponent(fieldAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblWeight)
                                .addComponent(fieldWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblFood)
                                .addComponent(fieldFood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCompany)
                            .addComponent(fieldCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPolicy)
                            .addComponent(fieldPolicy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCoverage)
                            .addComponent(fieldCL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEp)
                            .addComponent(fieldEp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRoom)
                            .addComponent(fieldRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldSD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSD))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fieldED, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblED))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModifty)
                    .addComponent(btnSave))
                .addGap(54, 54, 54))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldWeightActionPerformed

    private void fieldAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldAddressActionPerformed

    private void fieldFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldFoodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldFoodActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);

        Component[] componentArray = userProcessContainer.getComponents();
        if (componentArray.length > 0) {
            Component component = componentArray[componentArray.length - 1];
            if (component instanceof WelcomJpanel) {
                WelcomJpanel welcomePanel = (WelcomJpanel) component;
                welcomePanel.refreshTable();
            }
        }

        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_btnBackActionPerformed

    private void btnModiftyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModiftyActionPerformed
        // TODO add your handling code here:
        setFieldsEditable(true);
        btnModifty.setEnabled(false);
        btnSave.setEnabled(true);
    }//GEN-LAST:event_btnModiftyActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if (selectedRecord == null) {
            JOptionPane.showMessageDialog(this, "No selected records were saved.", "Warning", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 1. 验证和读取数据
        String ownerName = fieldOwnerName.getText();
        String petName = fieldPetName.getText();
        String species = fieldSpecies.getText();
        String roomNumber = fieldRoom.getText();
        
        if (ownerName.isEmpty() || petName.isEmpty() || species.isEmpty() || roomNumber.isEmpty()) {
            JOptionPane.showMessageDialog(this, "The names of the pet owner, the pet's name, the type of pet and the room number cannot be left blank.", "Warning", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            int age = Integer.parseInt(fieldAge.getText());
            double weight = Double.parseDouble(fieldWeight.getText());

            // 2. 更新 PetOwner 对象
            PetOwner owner = selectedRecord.getPet().getPetOwner();
            if (owner != null) {
                owner.setOwnerName(ownerName);
                owner.setPhone(fieldPhone.getText());
                owner.setAddress(fieldAddress.getText());
                owner.setEmail(fieldEmail.getText());
                owner.setEmergencyContact(fieldContact.getText());
            }

            // 3. 更新 Pet 对象
            Pet pet = selectedRecord.getPet();
            if (pet != null) {
                pet.setPetName(petName);
                pet.setSpecies(species);
                pet.setAge(age);
                pet.setWeight(weight);
                pet.setFoodAllergy(fieldFood.getText());
            }
            
            // 4. 更新 PetBoardingRecord 对象
            selectedRecord.setRoomNumber(roomNumber);
            selectedRecord.setStartDate(fieldSD.getText());
            selectedRecord.setEndDate(fieldED.getText());
            // 注意：不修改 Status，Status 应该通过工作流程按钮来修改
            
            // 5. 切换回只读模式
            setFieldsEditable(false);
            btnModifty.setEnabled(true);
            btnSave.setEnabled(false);

            JOptionPane.showMessageDialog(this, "Record update successful！", "success", JOptionPane.INFORMATION_MESSAGE);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Age and weight must be valid numbers.", "input error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "An error occurred during the saving process: " + e.getMessage(), "system error", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnModifty;
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField fieldAddress;
    private javax.swing.JTextField fieldAge;
    private javax.swing.JTextField fieldCL;
    private javax.swing.JTextField fieldCompany;
    private javax.swing.JTextField fieldContact;
    private javax.swing.JTextField fieldED;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JTextField fieldEp;
    private javax.swing.JTextField fieldFood;
    private javax.swing.JTextField fieldOwnerName;
    private javax.swing.JTextField fieldPetName;
    private javax.swing.JTextField fieldPhone;
    private javax.swing.JTextField fieldPolicy;
    private javax.swing.JTextField fieldRoom;
    private javax.swing.JTextField fieldSD;
    private javax.swing.JTextField fieldSpecies;
    private javax.swing.JTextField fieldWeight;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblBoarding;
    private javax.swing.JLabel lblCompany;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblCoverage;
    private javax.swing.JLabel lblED;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEp;
    private javax.swing.JLabel lblFood;
    private javax.swing.JLabel lblInsurance;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPet;
    private javax.swing.JLabel lblPetName;
    private javax.swing.JLabel lblPetowner;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPolicy;
    private javax.swing.JLabel lblRoom;
    private javax.swing.JLabel lblSD;
    private javax.swing.JLabel lblSpecies;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWeight;
    // End of variables declaration//GEN-END:variables

    private void setFieldsEditable(boolean editable) {
        fieldOwnerName.setEditable(editable);
        fieldPhone.setEditable(editable);
        fieldAddress.setEditable(editable);
        fieldEmail.setEditable(editable);
        fieldContact.setEditable(editable);
        
        fieldPetName.setEditable(editable);
        fieldSpecies.setEditable(editable);
        fieldAge.setEditable(editable);
        fieldWeight.setEditable(editable);
        fieldFood.setEditable(editable);
        
        fieldRoom.setEditable(editable);
        fieldSD.setEditable(editable);
        fieldED.setEditable(editable);
        
        fieldCompany.setEditable(editable);
        fieldPolicy.setEditable(editable);
        fieldCL.setEditable(editable);
        fieldEp.setEditable(editable);
    }
        
    // ⭐ 外部调用方法：用于加载指定记录的详细信息
    public void loadRecordDetails(PetBoardingRecord record) {
        
       this.selectedRecord = record;
    if (record == null) return;
    
    Pet pet = record.getPet();
    PetOwner owner = (pet != null) ? pet.getPetOwner() : null;

    // 假设您已在 Pet.java 中导入并定义了 InsurancePolicy 类
    // 如果您还没有 InsurancePolicy 类，请将 Business.Pet.InsurancePolicy 替换为实际的类名
    Business.Pet.InsurancePolicy policy = (pet != null) ? pet.getInsurancePolicy() : null;

    // 宠物主人信息 (Pet Owner)
    fieldOwnerName.setText((owner != null) ? owner.getOwnerName() : "");
    fieldPhone.setText((owner != null) ? owner.getPhone() : "");
    fieldAddress.setText((owner != null) ? owner.getAddress() : "");
    fieldEmail.setText((owner != null) ? owner.getEmail() : "");
    fieldContact.setText((owner != null) ? owner.getEmergencyContact() : "");

    // 宠物信息 (Pet)
    fieldPetName.setText((pet != null) ? pet.getPetName() : "");
    fieldSpecies.setText((pet != null) ? pet.getSpecies() : "");
    fieldAge.setText((pet != null) ? String.valueOf(pet.getAge()) : "");
    fieldWeight.setText((pet != null) ? String.valueOf(pet.getWeight()) : "");
    fieldFood.setText((pet != null) ? pet.getFoodAllergy() : ""); 
    // 假设 fieldFood 字段用于显示 Food Allergy，Food Preference 未在 UI 中

    // 寄养信息 (Boarding)
    fieldRoom.setText(record.getRoomNumber());
    fieldSD.setText(record.getStartDate());
    fieldED.setText(record.getEndDate());
    
   // ⭐ 修正：从 PetOwner 读取保险信息（不是从 Pet）
    if (owner != null) {
        fieldCompany.setText(owner.getInsuranceCompany() != null ? owner.getInsuranceCompany() : "N/A");
        fieldPolicy.setText(owner.getPolicyId() != null ? owner.getPolicyId() : "N/A");
        fieldCL.setText(owner.getCoverageLevel() != null ? owner.getCoverageLevel() : "N/A");
        fieldEp.setText(owner.getExpirationDate() != null ? owner.getExpirationDate() : "N/A");
    } else {
        fieldCompany.setText("N/A");
        fieldPolicy.setText("");
        fieldCL.setText("");
        fieldEp.setText("");
    }
    }
}
