/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Boarding;

import Business.Enterprise.Enterprise;
import Business.Enterprise.PetBoardingEnterprise;
import Business.Pet.BoardingRecordDirectory;
import Business.Pet.PetBoardingRecord;
import Business.PetBoardingOrganization.BoardingServiceOrganization;
import Business.Petsystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author hanlinyao
 */
public class WelcomJpanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private UserAccount account;
    private BoardingServiceOrganization organization; // 特定组织
    private Enterprise enterprise;
    private Petsystem system;

    /**
     * Creates new form WelcomJPanel
     */
    public WelcomJpanel(JPanel userProcessContainer, UserAccount account, 
                    BoardingServiceOrganization organization, Enterprise enterprise, Petsystem system) {
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;
        initComponents();
        // 初始加载表格数据
        populateTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPet = new javax.swing.JTable();
        btnRegister = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnRecord = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("Welcome!  Pet Caretaker");

        tblPet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Record ID", "Pet Name", "Specis", "Age", "Owner Name", "Start Date", "End Date", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblPet);

        btnRegister.setText("Register New Boarding Service");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnView.setText("View Details");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnRecord.setText("Record Today's Take");
        btnRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecordActionPerformed(evt);
            }
        });

        btnSubmit.setText("Submit Health Request");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnRegister, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(387, 387, 387)
                        .addComponent(btnLogout))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btnLogout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(22, 22, 22)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnRegister)
                .addGap(18, 18, 18)
                .addComponent(btnView)
                .addGap(18, 18, 18)
                .addComponent(btnRecord)
                .addGap(18, 18, 18)
                .addComponent(btnSubmit)
                .addContainerGap(64, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
         RegisterJpanel registerPanel = new RegisterJpanel(
            userProcessContainer, account, organization, enterprise, system);
        
        userProcessContainer.add("RegisterJpanel", registerPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
       
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        
        // ⭐ 核心逻辑：获取选中记录并跳转到 ViewJPanel
        int selectedRow = tblPet.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a foster care record to view.", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // 1. 获取选中的 Record ID (假设 ID 在第一列)
        String recordId = (String) tblPet.getValueAt(selectedRow, 0);

        // 2. 查找对应的 PetBoardingRecord 对象
        if (!(enterprise instanceof PetBoardingEnterprise)) {
            JOptionPane.showMessageDialog(this, "Incorrect enterprise type. Unable to retrieve records.", "Warning", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        PetBoardingEnterprise boardingEnt = (PetBoardingEnterprise) this.enterprise;
        BoardingRecordDirectory recordDirectory = boardingEnt.getBoardingRecordDirectory();

        PetBoardingRecord record = recordDirectory.findRecordById(recordId); 

        if (record == null) {
            JOptionPane.showMessageDialog(this, "The detailed information of this record was not found.", "Warning", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 3. 创建 ViewJPanel 实例
        ViewJPanel viewPanel = new ViewJPanel(
             userProcessContainer, account, organization, enterprise, system);

        // ⭐ 关键修正：调用 loadRecordDetails 方法，将数据对象传递给 ViewJPanel
        viewPanel.loadRecordDetails(record); 

        // 4. 切换到 ViewJPanel
        userProcessContainer.add("ViewJPanel", viewPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordActionPerformed
        // TODO add your handling code here:
         RecordJPanel recordPanel = new RecordJPanel(
            userProcessContainer, account, organization, enterprise, system);
        
        userProcessContainer.add("RegisterJpanel", recordPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnRecordActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
         SubmitJPanel submitPanel = new SubmitJPanel(
            userProcessContainer, account, organization, enterprise, system);
        
        userProcessContainer.add("RegisterJpanel", submitPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        java.awt.Component comp = this;

    // 向上遍历组件树，直到找到 MainJFrame
    while (comp != null && !(comp instanceof UI.admin.MainJFrame)) {
        comp = comp.getParent();
    }

    if (comp instanceof UI.admin.MainJFrame) {
        // ⭐ 关键修正：调用新的公共代理方法
        ((UI.admin.MainJFrame) comp).triggerLogout(); 
    } else {
        // 找不到 MainJFrame，执行后备方案
        if (userProcessContainer != null) {
            userProcessContainer.removeAll();
            userProcessContainer.revalidate();
            userProcessContainer.repaint();
        }
    }
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRecord;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPet;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
      DefaultTableModel model = (DefaultTableModel) tblPet.getModel();
    model.setRowCount(0);
    
    // ⭐ 关键修复：从 Enterprise 获取 BoardingRecordDirectory
    if (!(enterprise instanceof Business.Enterprise.PetBoardingEnterprise)) {
        JOptionPane.showMessageDialog(this, "Error: Current Enterprise is not PetBoardingEnterprise.", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    
    // 1. 获取正确的目录
    Business.Enterprise.PetBoardingEnterprise boardingEnt = (Business.Enterprise.PetBoardingEnterprise) this.enterprise;
    Business.Pet.BoardingRecordDirectory recordDirectory = boardingEnt.getBoardingRecordDirectory();
    
    try {
        if (recordDirectory != null && recordDirectory.getRecordList() != null) {
            for (PetBoardingRecord record : recordDirectory.getRecordList()) {
                Object[] row = new Object[8];
                
                // 确保 Pet 对象和 PetOwner 对象存在，以避免 NullPointerException
                Business.Pet.Pet pet = record.getPet();
                Business.Pet.PetOwner owner = (pet != null) ? pet.getPetOwner() : null;

                row[0] = record.getRecordId();
                row[1] = (pet != null) ? pet.getPetName() : "N/A";
                row[2] = (pet != null) ? pet.getSpecies() : "N/A";
                row[3] = (pet != null) ? pet.getAge() : "N/A";
                row[4] = (owner != null) ? owner.getOwnerName() : "N/A";
                row[5] = record.getStartDate();
                row[6] = record.getEndDate();
                row[7] = record.getStatus();

                model.addRow(row);
            }
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error retrieving boarding records: " + e.getMessage(), "Data Error", JOptionPane.ERROR_MESSAGE);
    }
    }

   public void refreshTable() {
    // 我们可以直接调用 populateTable() 来实现刷新功能
    populateTable();
}
}
