/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Boarding;

import Business.Enterprise.Enterprise;
import Business.Pet.BoardingRecordDirectory;
import Business.Pet.PetBoardingRecord;
import Business.PetBoardingOrganization.BoardingServiceOrganization;
import Business.Petsystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author hanlinyao
 */
public class WelcomJpanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private UserAccount account;
    private BoardingServiceOrganization organization; // 特定组织
    private Enterprise enterprise;
    private Petsystem system;

    /**
     * Creates new form WelcomJPanel
     */
    public WelcomJpanel(JPanel userProcessContainer, UserAccount account, 
                    BoardingServiceOrganization organization, Enterprise enterprise, Petsystem system) {
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = organization;
        this.enterprise = enterprise;
        this.system = system;
        initComponents();
        // 初始加载表格数据
        populateTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPet = new javax.swing.JTable();
        btnRegister = new javax.swing.JButton();
        btnView = new javax.swing.JButton();
        btnRecord = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("Welcome to  Pet Boarding Centre");

        tblPet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Record ID", "Pet Name", "Specis", "Age", "Owner Name", "Start Date", "End Date", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblPet);

        btnRegister.setText("Register New Boarding Service");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        btnView.setText("View Details");

        btnRecord.setText("Record Today's Take");

        btnSubmit.setText("Submit Health Request");

        btnLogout.setText("Logout");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(314, 314, 314)
                        .addComponent(btnLogout)
                        .addGap(14, 14, 14))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(23, 23, 23)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(76, 76, 76)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnRegister, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                                .addComponent(btnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSubmit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnLogout))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnRegister)
                .addGap(18, 18, 18)
                .addComponent(btnView)
                .addGap(18, 18, 18)
                .addComponent(btnRecord)
                .addGap(18, 18, 18)
                .addComponent(btnSubmit)
                .addContainerGap(98, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
      // 跳转到注册新寄养服务的面板
       
    }//GEN-LAST:event_btnRegisterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRecord;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPet;
    // End of variables declaration//GEN-END:variables

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblPet.getModel();
        model.setRowCount(0);
        
        // 假设 Boarding Service Organization 中包含 BoardingRecordDirectory
        // 实际中可能需要通过 Enterprise 或 Organization 的方法获取
        
        // 示例：从 Organization 的工作队列中加载请求（更常见）
        // for (WorkRequest request : organization.getWorkQueue().getWorkRequestList()) {
        //    // ...
        // }
        
        // 假设 BoardingServiceOrganization 有 getBoardingRecordDirectory()
        // 由于没有 BoardingServiceOrganization.java 的代码，我们假设记录存在于一个目录中：
        BoardingRecordDirectory recordDirectory = new BoardingRecordDirectory(); 
        
        if (recordDirectory.getRecordList() != null) {
            for (PetBoardingRecord record : recordDirectory.getRecordList()) {
                Object[] row = new Object[8];
                row[0] = record.getRecordId();
                row[1] = record.getPet().getPetName(); 
                row[2] = record.getPet().getSpecies();
                row[3] = record.getPet().getAge();
                row[4] = record.getPet().getPetOwner().getOwnerName();
                row[5] = record.getStartDate();
                row[6] = record.getEndDate();
                row[7] = record.getStatus();

                model.addRow(row);
            }
        }
    }
        
}
