package UI.enterpriseAdmin;

import Business.Enterprise.Enterprise;
import Business.Petsystem;
import Business.UserAccount.UserAccount;
import javax.swing.JPanel;

public class EnterpriseAdminWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private Petsystem system;
    private UserAccount account;

    // ⭐ 构造函数：从 Role 里传进来 4 个关键对象
    public EnterpriseAdminWorkAreaJPanel(JPanel userProcessContainer,
                                         UserAccount account,
                                         Enterprise enterprise,
                                         Petsystem system) {
        initComponents(); 

        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.system = system;
        this.account = account;

        // ⭐ 顶部欢迎语：显示真实用户名
        lblWelcome.setText("Welcome, " + account.getUsername() + "!");

        // ⭐ Enterprise 名称：显示 enterprise 名字，且不可编辑
        txtEnterprise.setText(enterprise.getName());
        txtEnterprise.setEditable(false);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enterpriseJPanel = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        lblTitle = new javax.swing.JLabel();
        lblEnterprise = new javax.swing.JLabel();
        txtEnterprise = new javax.swing.JTextField();
        btnManageOrg = new javax.swing.JButton();
        btnManageEmployees = new javax.swing.JButton();
        btnManageUsers = new javax.swing.JButton();

        setLayout(new java.awt.CardLayout());

        lblWelcome.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        lblWelcome.setText("Welcome, Enterprise Admin! ");

        btnLogOut.setText("Log Out ");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        lblTitle.setText("Enterprise Admin Work Area");

        lblEnterprise.setText("Enterprise:");

        txtEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnterpriseActionPerformed(evt);
            }
        });

        btnManageOrg.setText("Manage Organizations");
        btnManageOrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageOrgActionPerformed(evt);
            }
        });

        btnManageEmployees.setText("Manage Employees");

        btnManageUsers.setText("Manage Users");

        javax.swing.GroupLayout enterpriseJPanelLayout = new javax.swing.GroupLayout(enterpriseJPanel);
        enterpriseJPanel.setLayout(enterpriseJPanelLayout);
        enterpriseJPanelLayout.setHorizontalGroup(
            enterpriseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enterpriseJPanelLayout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addGroup(enterpriseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enterpriseJPanelLayout.createSequentialGroup()
                        .addComponent(lblWelcome)
                        .addGap(78, 78, 78)
                        .addComponent(btnLogOut)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enterpriseJPanelLayout.createSequentialGroup()
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(157, 157, 157))
                    .addGroup(enterpriseJPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(enterpriseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnManageOrg, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(enterpriseJPanelLayout.createSequentialGroup()
                                .addComponent(lblEnterprise)
                                .addGap(18, 18, 18)
                                .addComponent(txtEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnManageEmployees, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnManageUsers, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(enterpriseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE))
        );
        enterpriseJPanelLayout.setVerticalGroup(
            enterpriseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enterpriseJPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(enterpriseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLogOut))
                .addGap(42, 42, 42)
                .addComponent(lblTitle)
                .addGap(39, 39, 39)
                .addGroup(enterpriseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnterprise)
                    .addComponent(txtEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(btnManageOrg)
                .addGap(42, 42, 42)
                .addComponent(btnManageEmployees)
                .addGap(36, 36, 36)
                .addComponent(btnManageUsers)
                .addContainerGap(134, Short.MAX_VALUE))
            .addGroup(enterpriseJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enterpriseJPanelLayout.createSequentialGroup()
                    .addContainerGap(65, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(425, Short.MAX_VALUE)))
        );

        add(enterpriseJPanel, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void txtEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnterpriseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnterpriseActionPerformed

    private void btnManageOrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageOrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManageOrgActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnManageEmployees;
    private javax.swing.JButton btnManageOrg;
    private javax.swing.JButton btnManageUsers;
    private javax.swing.JPanel enterpriseJPanel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JTextField txtEnterprise;
    // End of variables declaration//GEN-END:variables
}
