/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.enterpriseAdmin;

import Business.Enterprise.Enterprise;
import Business.Enterprise.PetInsuranceEnterprise;
import Business.Petsystem;
import java.awt.CardLayout;
import javax.swing.JPanel;
import UI.Insurance.AgentDashboardJPanel;


/**
 *
 * @author jingyangwang
 */
public class ViewReportsJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private Petsystem system;
    /**
     * Creates new form ViewReportsJPanel
     */
    public ViewReportsJPanel(JPanel userProcessContainer, Enterprise enterprise, Petsystem system) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPetBoardingReport = new javax.swing.JButton();
        btnPetClinicReport = new javax.swing.JButton();
        btnPetInsuranceReport = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        btnPetBoardingReport.setText("Pet Boarding Report");

        btnPetClinicReport.setText("Pet Clinic Report");
        btnPetClinicReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPetClinicReportActionPerformed(evt);
            }
        });

        btnPetInsuranceReport.setText("Pet Insurance Report");
        btnPetInsuranceReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPetInsuranceReportActionPerformed(evt);
            }
        });

        btnBack.setText("<<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPetInsuranceReport)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnPetClinicReport, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPetBoardingReport, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(353, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(btnBack)
                .addGap(46, 46, 46)
                .addComponent(btnPetBoardingReport)
                .addGap(34, 34, 34)
                .addComponent(btnPetClinicReport)
                .addGap(33, 33, 33)
                .addComponent(btnPetInsuranceReport)
                .addContainerGap(223, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnPetClinicReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPetClinicReportActionPerformed
        // TODO add your handling code here:
        PetClinicReportJPanel panel = new PetClinicReportJPanel(userProcessContainer, enterprise, system);
        userProcessContainer.add("ClinicReportJPanel", panel);
        ((CardLayout) userProcessContainer.getLayout()).next(userProcessContainer);
    }//GEN-LAST:event_btnPetClinicReportActionPerformed

    private void btnPetInsuranceReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPetInsuranceReportActionPerformed
        // 只能在 PetInsuranceEnterprise 下看这个报表
    if (!(enterprise instanceof PetInsuranceEnterprise)) {
        javax.swing.JOptionPane.showMessageDialog(
                this,
                "This dashboard is only available for Pet Insurance Enterprise.");
        return;
    }

    PetInsuranceEnterprise insEnt = (PetInsuranceEnterprise) enterprise;

    // 这里我们暂时不需要 account 和 organization，可以先传 null
    AgentDashboardJPanel panel = new AgentDashboardJPanel(
            userProcessContainer,
            null,                      // UserAccount
            null,                      // InsurancePolicyOrganization
            insEnt,
            system
    );

    userProcessContainer.add("AgentDashboardJPanel", panel);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.next(userProcessContainer);
    }//GEN-LAST:event_btnPetInsuranceReportActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnPetBoardingReport;
    private javax.swing.JButton btnPetClinicReport;
    private javax.swing.JButton btnPetInsuranceReport;
    // End of variables declaration//GEN-END:variables
}
