package UI.Insurance;
import Business.Enterprise.Enterprise;
import Business.Enterprise.PetInsuranceEnterprise;
import Business.Organization.Organization;
import Business.Pet.InsurancePolicy;
import Business.Pet.InsurancePolicyDirectory;
import Business.Pet.Pet;
import Business.Pet.PetOwner;
import Business.Petsystem;
import Business.PetInsuranceOrganization.InsurancePolicyOrganization;
import Business.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.SwingUtilities;
import UI.admin.MainJFrame;


    public class AgentWorkAreaJPanel extends javax.swing.JPanel {
        private JPanel userProcessContainer; //Parent container used for switching between panels.
        private UserAccount account; //Logged-in agent account.
        private InsurancePolicyOrganization organization; //Organization that manages insurance policies.
        private PetInsuranceEnterprise insuranceEnterprise; //Insurance enterprise containing this organization.
        private Petsystem system; //Global system instance.
        private InsurancePolicyDirectory policyDirectory; //Directory containing all insurance policies.
   
    
    public AgentWorkAreaJPanel() {
        initComponents();
    }

    
    public AgentWorkAreaJPanel(JPanel userProcessContainer,
                               UserAccount account,
                               Organization organization,
                               Enterprise enterprise,
                               Petsystem system) {

        initComponents();

        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.organization = (InsurancePolicyOrganization) organization;
        this.insuranceEnterprise = (PetInsuranceEnterprise) enterprise;
        this.system = system;
        this.policyDirectory = system.getInsurancePolicyDirectory();

        populatePolicyTable();
    }
    
    
    public void populatePolicyTable() {
        DefaultTableModel model = (DefaultTableModel) tblPolicyList.getModel();
        model.setRowCount(0);

        if (policyDirectory == null) {
            return;
        }

        for (InsurancePolicy policy : policyDirectory.getPolicyList()) {
            Object[] row = new Object[7];

            row[0] = policy;

            Pet pet = policy.getPet();
            String petName = "";
            String ownerName = "";

            if (pet != null) {
                petName = pet.getPetName();
                PetOwner owner = pet.getPetOwner();
                if (owner != null) {
                    ownerName = owner.getOwnerName();
                }
            }

            row[1] = petName;
            row[2] = ownerName;
            row[3] = policy.getCoverageType();
            row[4] = policy.getStartDate();
            row[5] = policy.getEndDate();
            row[6] = (policy.getStatus() == null || policy.getStatus().isEmpty())
            ? "Active"
            : policy.getStatus();

            model.addRow(row);
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogout = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPolicyList = new javax.swing.JTable();
        lblPolicyList = new javax.swing.JLabel();
        btnCreateNew = new javax.swing.JButton();
        btnViewPolicy = new javax.swing.JButton();
        btnDashboard = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));
        setForeground(new java.awt.Color(242, 242, 242));

        btnLogout.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Microsoft YaHei UI", 3, 24)); // NOI18N
        lblTitle.setText("Welcome Insurance Policy Management");

        tblPolicyList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Policy ID", "Pet Name", "Owner Name", "Coverage Type", "Start Date", "Expiration Date", "Status"
            }
        ));
        jScrollPane1.setViewportView(tblPolicyList);

        lblPolicyList.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        lblPolicyList.setText("Policy List:");

        btnCreateNew.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        btnCreateNew.setText("Create New Policy");
        btnCreateNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateNewActionPerformed(evt);
            }
        });

        btnViewPolicy.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        btnViewPolicy.setText("View Policy");
        btnViewPolicy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPolicyActionPerformed(evt);
            }
        });

        btnDashboard.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        btnDashboard.setText("View Insurance Dashboard");
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLogout))
                        .addComponent(lblPolicyList)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 853, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnViewPolicy, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCreateNew, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)))
                    .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle)
                    .addComponent(btnLogout))
                .addGap(18, 18, 18)
                .addComponent(lblPolicyList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnCreateNew)
                .addGap(40, 40, 40)
                .addComponent(btnViewPolicy)
                .addGap(39, 39, 39)
                .addComponent(btnDashboard)
                .addContainerGap(65, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateNewActionPerformed
    AgentCreatePolicyJPanel createPanel = new AgentCreatePolicyJPanel(
                                            userProcessContainer,
                                            account,
                                            organization,
                                            insuranceEnterprise,
                                            system);
       userProcessContainer.add("AgentCreatePolicyJPanel", createPanel);
       CardLayout layout = (CardLayout) userProcessContainer.getLayout();
       layout.show(userProcessContainer, "AgentCreatePolicyJPanel");
    }//GEN-LAST:event_btnCreateNewActionPerformed

    private void btnViewPolicyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPolicyActionPerformed
    int selectedRow = tblPolicyList.getSelectedRow();
        if (selectedRow < 0) {
        JOptionPane.showMessageDialog(this,
                "Please select a policy from the table first.",
                "Warning",
                JOptionPane.WARNING_MESSAGE);
        return;
    }

    InsurancePolicy selectedPolicy = (InsurancePolicy) tblPolicyList.getValueAt(selectedRow, 0);

    AgentManagePolicyJPanel managePanel = new AgentManagePolicyJPanel(
                                                userProcessContainer,
                                                account,
                                                organization,
                                                insuranceEnterprise,
                                                system,
                                                selectedPolicy
    );
    userProcessContainer.add("AgentManagePolicyJPanel", managePanel);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.show(userProcessContainer, "AgentManagePolicyJPanel");
    }//GEN-LAST:event_btnViewPolicyActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
    java.awt.Window window = SwingUtilities.getWindowAncestor(this);
    if (window instanceof MainJFrame) {
        MainJFrame frame = (MainJFrame) window;
        frame.triggerLogout();
    }
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        AgentDashboardJPanel panel = new AgentDashboardJPanel(
                                                    userProcessContainer,
                                                    account,
                                                    organization,
                                                    insuranceEnterprise,
                                                    system
        );
        userProcessContainer.add("AgentDashboardJPanel", panel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.show(userProcessContainer, "AgentDashboardJPanel");
    }//GEN-LAST:event_btnDashboardActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateNew;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnViewPolicy;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPolicyList;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblPolicyList;
    // End of variables declaration//GEN-END:variables
}
