/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Insurance;
import Business.UserAccount.UserAccount;
import Business.Petsystem;
import Business.Enterprise.PetInsuranceEnterprise;
import Business.PetInsuranceOrganization.InsuranceClaimOrganization;
import Business.WorkQueue.InsuranceClaimRequest;
import Business.WorkQueue.WorkRequest;
import UI.admin.MainJFrame;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eve Dou
 */
public class ClaimProcessorWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private UserAccount account;
    private InsuranceClaimOrganization organization;
    private PetInsuranceEnterprise enterprise;
    private Petsystem system;
    private InsuranceClaimOrganization claimOrg; 

    /**
     * Creates new form ClaimProcessorWorkAreaJPanel
     */
    public ClaimProcessorWorkAreaJPanel(JPanel userProcessContainer,
                                        UserAccount account,
                                        InsuranceClaimOrganization organization,
                                        PetInsuranceEnterprise enterprise,
                                        Petsystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.account = account;
        this.claimOrg = organization; 
        this.enterprise = enterprise;
        this.system = system;
        
        populateTable();
    }
    
     private void populateTable() {
    DefaultTableModel model = (DefaultTableModel) tblInsuranceClaim.getModel();
    model.setRowCount(0);

    for (WorkRequest req : claimOrg.getWorkQueue().getWorkRequestList()) {

        if (req instanceof InsuranceClaimRequest) {
            InsuranceClaimRequest claim = (InsuranceClaimRequest) req;

            Object[] row = new Object[11];
            row[0]  = claim.getHolderName();        // Holder Name
            row[1]  = claim.getPatientId();         // Patient ID
            row[2]  = claim.getPolicyId();          // Policy ID
            row[3]  = claim.getPetName();           // Pet Name
            row[4]  = claim.getSymptom();           // Symptom
            row[5]  = claim.getLabResult();         // Lab Result
            row[6]  = claim.getTreatmentCost();     // Treatment Cost
            row[7]  = claim.getClaimAmount();       // Claim Amount
            row[8]  = claim.getSender();            // Sender
            row[9]  = claim.getStatus();            // Status (Pending/Approved/Rejected)
            row[10] = claim.getCoverageDecision();  // Decision 全保/半保

            model.addRow(row);
        }
    }

}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblInsuranceClaimProcess = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInsuranceClaim = new javax.swing.JTable();
        btnPolicyRecord = new javax.swing.JButton();
        btnViewDetail = new javax.swing.JButton();
        lblClaimList = new javax.swing.JLabel();
        btnApprove = new javax.swing.JButton();
        btnReject = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        lblInsuranceClaimProcess.setFont(new java.awt.Font("Microsoft YaHei UI", 3, 24)); // NOI18N
        lblInsuranceClaimProcess.setText("Welcome Insurance Claim Management ");

        btnLogOut.setText("Logout");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        tblInsuranceClaim.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Patient ID", "Policy ID", "Holder Name", "Pet Name", "Symptom", "Lab Result", "Treatment Cost", "Claim Amount", "Sender", "Status", "Decision"
            }
        ));
        jScrollPane1.setViewportView(tblInsuranceClaim);

        btnPolicyRecord.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        btnPolicyRecord.setText("View Policy Record");
        btnPolicyRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPolicyRecordActionPerformed(evt);
            }
        });

        btnViewDetail.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        btnViewDetail.setText("View Claim Details");
        btnViewDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDetailActionPerformed(evt);
            }
        });

        lblClaimList.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        lblClaimList.setText("Claim List:");

        btnApprove.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        btnApprove.setText("Approve");
        btnApprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveActionPerformed(evt);
            }
        });

        btnReject.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        btnReject.setText("Reject");
        btnReject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRejectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblClaimList, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(1056, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnViewDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPolicyRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnReject, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnApprove, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(200, 200, 200))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblInsuranceClaimProcess)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogOut)
                        .addGap(54, 54, 54))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInsuranceClaimProcess)
                    .addComponent(btnLogOut))
                .addGap(34, 34, 34)
                .addComponent(lblClaimList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewDetail)
                    .addComponent(btnApprove))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReject)
                    .addComponent(btnPolicyRecord))
                .addContainerGap(92, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
   // 找到这个 panel 所在的顶层窗口（JFrame）
    java.awt.Window window = SwingUtilities.getWindowAncestor(this);

    if (window instanceof MainJFrame) {
        MainJFrame mainFrame = (MainJFrame) window;
        // 复用 MainJFrame 里已经写好的登出逻辑
        mainFrame.triggerLogout();
    } else {
        // 兜底：如果拿不到 MainJFrame，就仅仅从 CardLayout 返回上一页
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnViewDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDetailActionPerformed
        // 1. 检查有没有选中表格行
        int selectedRow = tblInsuranceClaim.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(
                    this,
                    "Please select a claim first.",
                    "Warning",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        // 2. 通过 Policy ID 在 workQueue 里找到对应的 InsuranceClaimRequest
        String policyId = (String) tblInsuranceClaim.getValueAt(selectedRow, 1);

        InsuranceClaimRequest targetClaim = null;
        for (WorkRequest req : claimOrg.getWorkQueue().getWorkRequestList()) {
            if (req instanceof InsuranceClaimRequest) {
                InsuranceClaimRequest ic = (InsuranceClaimRequest) req;
                if (policyId.equals(ic.getPolicyId())) {
                    targetClaim = ic;
                    break;
                }
            }
        }

        if (targetClaim == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "Cannot find this claim in work queue.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        // 3. 跳转到 ClaimDetailJPanel，并把这条 claim 传过去
        ClaimDetailJPanel detailPanel = new ClaimDetailJPanel(userProcessContainer, targetClaim);
        userProcessContainer.add("ClaimDetailJPanel", detailPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnViewDetailActionPerformed

    private void btnApproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveActionPerformed
            // 1. 看看有没有选中行
            int selectedRow = tblInsuranceClaim.getSelectedRow();
            if (selectedRow < 0) {
                JOptionPane.showMessageDialog(
                        this,
                        "Please select a claim first.",
                        "Warning",
                        JOptionPane.WARNING_MESSAGE
                );
                return;
            }

            // 2. 从表格里拿到 policyId（第二列，索引 1）
            String policyId = (String) tblInsuranceClaim.getValueAt(selectedRow, 1);

            // 3. 在 claimOrg 的 workQueue 里找到这一条 InsuranceClaimRequest
            InsuranceClaimRequest targetClaim = null;
            for (WorkRequest req : claimOrg.getWorkQueue().getWorkRequestList()) {
                if (req instanceof InsuranceClaimRequest) {
                    InsuranceClaimRequest ic = (InsuranceClaimRequest) req;
                    if (policyId.equals(ic.getPolicyId())) {
                        targetClaim = ic;
                        break;
                    }
                }
            }

            if (targetClaim == null) {
                JOptionPane.showMessageDialog(
                        this,
                        "Cannot find this claim in work queue.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }

            // 4. 如果已经处理过，就不重复处理
            if ("Approved".equalsIgnoreCase(targetClaim.getStatus())) {
                JOptionPane.showMessageDialog(
                        this,
                        "This claim is already approved.",
                        "Info",
                        JOptionPane.INFORMATION_MESSAGE
                );
                return;
            }
            if ("Rejected".equalsIgnoreCase(targetClaim.getStatus())) {
                JOptionPane.showMessageDialog(
                        this,
                        "This claim has been rejected.",
                        "Info",
                        JOptionPane.INFORMATION_MESSAGE
                );
                return;
            }

            // 5. 修改状态 + 决策
            targetClaim.setStatus("Approved");
            targetClaim.setClaimDecision("Approved");

            JOptionPane.showMessageDialog(
                    this,
                    "Claim approved successfully.",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE
            );

            // 6. 刷新表格
            populateTable();
    }//GEN-LAST:event_btnApproveActionPerformed

    private void btnRejectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRejectActionPerformed
    // 1. 看看有没有选中行
    int selectedRow = tblInsuranceClaim.getSelectedRow();
    if (selectedRow < 0) {
        JOptionPane.showMessageDialog(
                this,
                "Please select a claim first.",
                "Warning",
                JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    // 2. 从表格里拿到 policyId（第二列，索引 1）
    String policyId = (String) tblInsuranceClaim.getValueAt(selectedRow, 1);

    // 3. 在 claimOrg 的 workQueue 里找到这一条 InsuranceClaimRequest
    InsuranceClaimRequest targetClaim = null;
    for (WorkRequest req : claimOrg.getWorkQueue().getWorkRequestList()) {
        if (req instanceof InsuranceClaimRequest) {
            InsuranceClaimRequest ic = (InsuranceClaimRequest) req;
            if (policyId.equals(ic.getPolicyId())) {
                targetClaim = ic;
                break;
            }
        }
    }

    if (targetClaim == null) {
        JOptionPane.showMessageDialog(
                this,
                "Cannot find this claim in work queue.",
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
        return;
    }

    // 4. 如果已经处理过，就不重复处理
    if ("Rejected".equalsIgnoreCase(targetClaim.getStatus())) {
        JOptionPane.showMessageDialog(
                this,
                "This claim is already rejected.",
                "Info",
                JOptionPane.INFORMATION_MESSAGE
        );
        return;
    }
    if ("Approved".equalsIgnoreCase(targetClaim.getStatus())) {
        JOptionPane.showMessageDialog(
                this,
                "This claim has been approved and cannot be rejected.",
                "Info",
                JOptionPane.INFORMATION_MESSAGE
        );
        return;
    }

    // 5. 二次确认（可选）
    int result = JOptionPane.showConfirmDialog(
            this,
            "Are you sure to reject this claim?",
            "Confirm",
            JOptionPane.YES_NO_OPTION
    );
    if (result != JOptionPane.YES_OPTION) {
        return;
    }

    // 6. 修改状态 + 决策
    targetClaim.setStatus("Rejected");
    targetClaim.setClaimDecision("Rejected");

    JOptionPane.showMessageDialog(
            this,
            "Claim rejected.",
            "Success",
            JOptionPane.INFORMATION_MESSAGE
    );

    // 7. 刷新表格
    populateTable();
    }//GEN-LAST:event_btnRejectActionPerformed

    private void btnPolicyRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPolicyRecordActionPerformed
            ClaimPolicyRecordJPanel panel =
            new ClaimPolicyRecordJPanel(userProcessContainer, claimOrg);
    userProcessContainer.add("ClaimPolicyRecordJPanel", panel);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.next(userProcessContainer);
    }//GEN-LAST:event_btnPolicyRecordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApprove;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnPolicyRecord;
    private javax.swing.JButton btnReject;
    private javax.swing.JButton btnViewDetail;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblClaimList;
    private javax.swing.JLabel lblInsuranceClaimProcess;
    private javax.swing.JTable tblInsuranceClaim;
    // End of variables declaration//GEN-END:variables
}
