/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Insurance;

import Business.Organization.Organization;
import Business.WorkQueue.InsuranceClaimRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author Eve Dou
 */
public class ClaimPolicyRecordJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private Organization claimOrg;  // InsuranceClaim Organization
    /**
     * Creates new form PolicyRecordJPanel
     */
    public ClaimPolicyRecordJPanel(JPanel userProcessContainer, Organization claimOrg) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.claimOrg = claimOrg;
    }

     private void populateFromClaim(InsuranceClaimRequest claim) {
        // 上面的搜索区
        txtPolicyId.setText(claim.getPolicyId());
        // txtPolicyHolderName 目前没有字段来源，先留空或以后扩展

        // 左边 Policy Basic Information
        txtCompany.setText(claim.getInsuranceCompany());
        txtPolicyHolderName.setText(claim.getHolderName()); 
        txtPetName.setText(claim.getPetName());
        txtCoverage.setText(claim.getCoverageLevel());
        txtExpiration.setText(claim.getExpirationDate());
        txtStatus.setText(claim.getStatus());   // WorkRequest.status

         // 右边 Policy Claim History
        if (claim.getRequestDate() != null) {
            txtDate.setText(String.valueOf(claim.getRequestDate()));
        } else {
            txtDate.setText("");
        }

        // ✅ 用真正的 ClaimId
        txtClaimID.setText(String.valueOf(claim.getClaimId()));

        // 赔付金额（Approve 时算好的）
        txtAmount.setText(String.valueOf(claim.getClaimAmount()));

        String decision = claim.getClaimDecision();
        if (decision == null || decision.isEmpty()) {
            decision = "Pending";
        }
        txtResult.setText(decision);
    }
     
     private void clearFields() {
        // 左侧
        txtCompany.setText("");
        txtPetName.setText("");
        txtCoverage.setText("");
        txtExpiration.setText("");
        txtStatus.setText("");

        // 右侧
        txtDate.setText("");
        txtClaimID.setText("");
        txtAmount.setText("");
        txtResult.setText("");
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPolicyRecord = new javax.swing.JLabel();
        lblPolicyID = new javax.swing.JLabel();
        txtPolicyId = new javax.swing.JTextField();
        lblPolicyHolder = new javax.swing.JLabel();
        txtPolicyHolderName = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        lblPetName = new javax.swing.JLabel();
        lblCoverageType = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblExpirationDate = new javax.swing.JLabel();
        txtPetName = new javax.swing.JTextField();
        txtCoverage = new javax.swing.JTextField();
        txtStatus = new javax.swing.JTextField();
        txtExpiration = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        lblPolicyBasic = new javax.swing.JLabel();
        txtCompany = new javax.swing.JTextField();
        lblCompany = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        lblClaimID = new javax.swing.JLabel();
        lblAmount = new javax.swing.JLabel();
        lblClaimHistory = new javax.swing.JLabel();
        lblResult = new javax.swing.JLabel();
        txtDate = new javax.swing.JTextField();
        txtClaimID = new javax.swing.JTextField();
        txtAmount = new javax.swing.JTextField();
        txtResult = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 204, 102));

        lblPolicyRecord.setFont(new java.awt.Font("Microsoft YaHei UI", 3, 24)); // NOI18N
        lblPolicyRecord.setText("Policy Record Detail");

        lblPolicyID.setText("Policy ID: ");

        lblPolicyHolder.setText("Policy Holder Name: ");

        btnSearch.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        lblPetName.setText("Pet Name:");

        lblCoverageType.setText("Coverage Type:");

        lblStatus.setText("Status:");

        lblExpirationDate.setText("Expiration Date:");

        txtStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStatusActionPerformed(evt);
            }
        });

        btnBack.setText("<<Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblPolicyBasic.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        lblPolicyBasic.setText("Policy Basic Information:");

        lblCompany.setText("Insurance Company: ");

        lblDate.setText("Date:");

        lblClaimID.setText("Claim ID:");

        lblAmount.setText("Amount:");

        lblClaimHistory.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        lblClaimHistory.setText("Policy Claim History:");

        lblResult.setText("Result:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBack)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblPolicyBasic)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblPolicyHolder, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPolicyHolderName, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblExpirationDate, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(51, 51, 51)
                                            .addComponent(txtExpiration, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblCoverageType, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtCoverage, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblPetName, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtPetName, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(95, 95, 95)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblClaimHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblAmount)
                                            .addComponent(lblClaimID, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtClaimID, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(0, 83, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblPolicyID, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtPolicyId, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(198, 198, 198)
                                .addComponent(lblPolicyRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPolicyRecord)
                    .addComponent(btnBack))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPolicyId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPolicyID)
                    .addComponent(btnSearch))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPolicyBasic)
                    .addComponent(lblClaimHistory))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCompany, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCompany)
                            .addComponent(lblDate))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblClaimID)
                                .addGap(18, 18, 18)
                                .addComponent(lblAmount)
                                .addGap(16, 16, 16)
                                .addComponent(lblResult))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPolicyHolder)
                                    .addComponent(txtPolicyHolderName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPetName)
                                    .addComponent(txtPetName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCoverageType)
                                    .addComponent(txtCoverage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblExpirationDate)
                                    .addComponent(txtExpiration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblStatus)
                                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtClaimID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(131, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStatusActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
    userProcessContainer.remove(this);
    CardLayout layout = (CardLayout) userProcessContainer.getLayout();
    layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String policyId = txtPolicyId.getText().trim();

        if (policyId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a Policy ID.");
            return;
        }

        InsuranceClaimRequest match = null;

        // 在 claimOrg 的 workQueue 中用 policyId 查找对应的 InsuranceClaimRequest
        for (WorkRequest req : claimOrg.getWorkQueue().getWorkRequestList()) {
            if (req instanceof InsuranceClaimRequest) {
                InsuranceClaimRequest ic = (InsuranceClaimRequest) req;
                if (policyId.equals(ic.getPolicyId())) {
                    match = ic;
                    break;
                }
            }
        }

        if (match == null) {
            JOptionPane.showMessageDialog(this,
                    "No record found for Policy ID: " + policyId);
            clearFields();
            return;
        }

        // 找到了，填充下面的字段
        populateFromClaim(match);
    }//GEN-LAST:event_btnSearchActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblClaimHistory;
    private javax.swing.JLabel lblClaimID;
    private javax.swing.JLabel lblCompany;
    private javax.swing.JLabel lblCoverageType;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblExpirationDate;
    private javax.swing.JLabel lblPetName;
    private javax.swing.JLabel lblPolicyBasic;
    private javax.swing.JLabel lblPolicyHolder;
    private javax.swing.JLabel lblPolicyID;
    private javax.swing.JLabel lblPolicyRecord;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtClaimID;
    private javax.swing.JTextField txtCompany;
    private javax.swing.JTextField txtCoverage;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtExpiration;
    private javax.swing.JTextField txtPetName;
    private javax.swing.JTextField txtPolicyHolderName;
    private javax.swing.JTextField txtPolicyId;
    private javax.swing.JTextField txtResult;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables
}
