/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.admin;

import Business.ConfigureABusiness;
import Business.Petsystem;
import Business.UserAccount.UserAccount;
import Business.Role.SystemAdminRole; // 导入 SystemAdminRole 以便在登录后判断角色
import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author hanlinyao
 */
public class MainJFrame extends javax.swing.JFrame {
    private Petsystem system;
    private UserAccount userAccount; // 当前登录的用户

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        // 在 initComponents() 之前初始化系统实例
        ConfigureABusiness.configure();
        this.system = Petsystem.getInstance();
        initComponents();
        
        // 初始状态设置
        jSplitPane1.setLeftComponent(jPanel1);
        container.removeAll(); // 清空右侧工作区
        btnLogout.setEnabled(false); // 初始状态禁用登出按钮
        
        // 默认将窗口最大化或设置一个合理大小
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        container = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("User Name");

        jLabel2.setText("Password");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(29, Short.MAX_VALUE))
            .addComponent(jTextField1)
            .addComponent(jTextField2)
            .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnLogin)
                .addGap(26, 26, 26)
                .addComponent(btnLogout)
                .addContainerGap(303, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        container.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(container);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // 1. 获取用户输入
        String userName = jTextField1.getText(); // 用户名
        String password = jTextField2.getText(); // 密码 (注意：jTextField2 最好是 JPasswordField)
        
        // 2. 验证用户
        UserAccount userAccount = system.getUserAccountDirectory().authenticateUser(userName, password);
        
        if (userAccount == null) {
            // 验证失败
            JOptionPane.showMessageDialog(this, "用户名或密码错误！", "登录失败", JOptionPane.ERROR_MESSAGE);
            return;
        } else {
            // 验证成功
            this.userAccount = userAccount;
            
            // 3. 登录成功后的 UI 切换
            jPanel1.setVisible(false); // 隐藏左侧登录面板
            btnLogout.setEnabled(true); // 启用登出按钮
            
            // 4. 加载用户工作区
            loadWorkArea();
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
       // 1. 清除当前用户会话
        this.userAccount = null;
    
    // 2. 恢复登录界面
    getContentPane().removeAll(); // 清空当前内容
    getContentPane().setLayout(new java.awt.CardLayout()); // 重新设置布局
    getContentPane().add(jSplitPane1, "card2"); // 添加回登录界面
    
    // 3. 重置登录面板状态
    jPanel1.setVisible(true); // 显示左侧登录面板
    container.removeAll(); // 清除右侧工作区内容
    container.revalidate();
    container.repaint();
    
    btnLogout.setEnabled(false); // 禁用登出按钮
    
    // 4. 清空输入框
    jTextField1.setText("");
    jTextField2.setText("");
    
    // 5. 刷新界面
    getContentPane().revalidate();
    getContentPane().repaint();
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JPanel container;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

    private void loadWorkArea() {
       if (userAccount == null) return;

    JPanel workAreaPanel = null;
    
    // 检查是否是系统管理员
    if (userAccount.getRole() instanceof SystemAdminRole) {
        // 创建工作区面板
        workAreaPanel = new SystemAdminWorkAreaJPanel(system); 
    } 
    // 您可以在这里添加其他角色的判断

    if (workAreaPanel != null) {
        // ⭐ 关键修改：移除整个 jSplitPane1，用工作区面板替换
        getContentPane().removeAll(); // 清空所有内容
        getContentPane().setLayout(new java.awt.BorderLayout()); // 设置布局
        getContentPane().add(workAreaPanel, java.awt.BorderLayout.CENTER); // 添加工作区
        
        // 刷新界面
        getContentPane().revalidate();
        getContentPane().repaint();
    }
    }

    private void setupActionListeners() {
        // 绑定登录按钮事件
        btnLogin.addActionListener(this::btnLoginActionPerformed);
        
        // 绑定登出按钮事件
        btnLogout.addActionListener(this::btnLogoutActionPerformed);
    }
       
        
}
