/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.admin;

import Business.Petsystem;
import Business.Network.Network;
import Business.Enterprise.Enterprise;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import UI.admin.SystemAdminWorkAreaJPanel;
import javax.swing.event.TreeSelectionEvent;
import UI.admin.MainJFrame;



public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {
    private Petsystem system;
    
    

    public SystemAdminWorkAreaJPanel(Petsystem system) {
      this.system = system;
    initComponents();
    
    jTree1.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
        public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
            jTree1ValueChanged(evt);
            jTree1.updateUI(); 
        }

          private void jTree1ValueChanged(TreeSelectionEvent evt) {
              
    DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) jTree1.getLastSelectedPathComponent();
    if (selectedNode != null && selectedNode.getUserObject() instanceof Network) {
        Network network = (Network) selectedNode.getUserObject();
        // System.out.println("Selected Network: " + network.getName()); 
    }
          }
              
    });
    
    
    populateTree();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanel2 = new javax.swing.JPanel();
        btnManageNetwork = new javax.swing.JButton();
        btnManageEnterprise = new javax.swing.JButton();
        btnMea = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(jTree1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );

        jSplitPane1.setLeftComponent(jPanel1);

        btnManageNetwork.setText("Manage Network");
        btnManageNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageNetworkActionPerformed(evt);
            }
        });

        btnManageEnterprise.setText("Manage Enterprise");
        btnManageEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEnterpriseActionPerformed(evt);
            }
        });

        btnMea.setText("Manage Enterprise Admin");
        btnMea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMeaActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMea, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnManageNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(btnLogout)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnManageNetwork))
                    .addComponent(btnLogout))
                .addGap(29, 29, 29)
                .addComponent(btnManageEnterprise)
                .addGap(31, 31, 31)
                .addComponent(btnMea)
                .addContainerGap(329, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel2);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageNetworkActionPerformed

    ManageNetworkJPanel manageNetworkJPanel = new ManageNetworkJPanel(system, this);
        jSplitPane1.setRightComponent(manageNetworkJPanel);
        jSplitPane1.setDividerLocation(150);
        jSplitPane1.revalidate();
    }//GEN-LAST:event_btnManageNetworkActionPerformed

    private void btnManageEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEnterpriseActionPerformed

        ManageEnterpriseJPanel manageEnterpriseJPanel = new ManageEnterpriseJPanel(system, this);
        jSplitPane1.setRightComponent(manageEnterpriseJPanel);
        jSplitPane1.setDividerLocation(150);
        jSplitPane1.revalidate();
     
    }//GEN-LAST:event_btnManageEnterpriseActionPerformed

    private void btnMeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMeaActionPerformed

         ManageEnterpriseAdminJPanel manageEnterpriseAdminJPanel = new ManageEnterpriseAdminJPanel(system, this);
        jSplitPane1.setRightComponent(manageEnterpriseAdminJPanel);
        jSplitPane1.setDividerLocation(150);
        jSplitPane1.revalidate();
    }//GEN-LAST:event_btnMeaActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed

    int choice = JOptionPane.showConfirmDialog(this, 
        "Are you sure you want to logout?", 
        "Confirm Logout", 
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE);
    
    if (choice == JOptionPane.YES_OPTION) {
        java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);
        
        if (window instanceof MainJFrame) {
            MainJFrame mainFrame = (MainJFrame) window;
            mainFrame.triggerLogout(); 
        }
    }
        
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageEnterprise;
    private javax.swing.JButton btnManageNetwork;
    private javax.swing.JButton btnMea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables

    void populateTree() {

    DefaultTreeModel model = (DefaultTreeModel) jTree1.getModel();

    DefaultMutableTreeNode root = new DefaultMutableTreeNode("PetCareSystem");
    model.setRoot(root); 
    
    if (system.getNetworkList() != null) {
        for (Network network : system.getNetworkList()) {
           
            DefaultMutableTreeNode networkNode = new DefaultMutableTreeNode(network);
            root.add(networkNode);
      
            if (network.getEnterpriseDirectory() != null) {
                for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                    DefaultMutableTreeNode enterpriseNode = new DefaultMutableTreeNode(enterprise);
                    networkNode.add(enterpriseNode);
                }
            }
        }
    }

    model.reload(root); 
    
  
    for (int i = 0; i < jTree1.getRowCount(); i++) {
        jTree1.expandRow(i);
    }
        
    }

    private void loadManageAdminPanel() {
        try {
       
        ManageEnterpriseAdminJPanel manageEnterpriseAdminJPanel = new ManageEnterpriseAdminJPanel(system, this);
    
        jPanel2.removeAll(); 

        jPanel2.add("manageEnterpriseAdminJPanel", manageEnterpriseAdminJPanel);
        
        CardLayout layout = (CardLayout)jPanel2.getLayout();
        layout.show(jPanel2, "manageEnterpriseAdminJPanel");
        
        jPanel2.revalidate();
        jPanel2.repaint();
        
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Failed to load the management panel:" + ex.getMessage(), "Internal error", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace(); 
    }
    }

    void restoreDefaultView() {

    jSplitPane1.setRightComponent(jPanel2); 

    jSplitPane1.setDividerLocation(150); 

    jSplitPane1.revalidate();
    jSplitPane1.repaint(); 
    
    populateTree();
    }
        
}
