/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.admin;

import Business.Petsystem;
import Business.Network.Network;
import Business.Enterprise.Enterprise;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import UI.admin.SystemAdminWorkAreaJPanel;
import javax.swing.event.TreeSelectionEvent;
import UI.admin.MainJFrame;


/**
 *
 * @author hanlinyao
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {
    private Petsystem system;
    
    

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    public SystemAdminWorkAreaJPanel(Petsystem system) {
      this.system = system;
    initComponents();
    // ⭐ 添加 JTree 监听器
    jTree1.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
        public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
            jTree1ValueChanged(evt);
            jTree1.updateUI(); // ⭐ 关键：强制刷新 JTree 视图
        }

          private void jTree1ValueChanged(TreeSelectionEvent evt) {
              // 这个方法通常用来处理节点点击，但我们在这里主要利用它的触发机制。
    // 如果您需要根据选中的节点显示信息，代码应该写在这里。
    
    // 假设您想在点击节点时显示节点的名称：
    DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) jTree1.getLastSelectedPathComponent();
    if (selectedNode != null && selectedNode.getUserObject() instanceof Network) {
        Network network = (Network) selectedNode.getUserObject();
        // 可以在这里设置一个标签来显示选中的网络名称，以确认 JTree 正在工作
        // System.out.println("Selected Network: " + network.getName()); 
    }
          }
              
    });
    
    
    // 初始化 JTree
    populateTree();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        jPanel2 = new javax.swing.JPanel();
        btnManageNetwork = new javax.swing.JButton();
        btnManageEnterprise = new javax.swing.JButton();
        btnMea = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setViewportView(jTree1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );

        jSplitPane1.setLeftComponent(jPanel1);

        btnManageNetwork.setText("Manage Network");
        btnManageNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageNetworkActionPerformed(evt);
            }
        });

        btnManageEnterprise.setText("Manage Enterprise");
        btnManageEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEnterpriseActionPerformed(evt);
            }
        });

        btnMea.setText("Manage Enterprise Admin");
        btnMea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMeaActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMea, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnManageNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(btnLogout)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(btnManageNetwork))
                    .addComponent(btnLogout))
                .addGap(29, 29, 29)
                .addComponent(btnManageEnterprise)
                .addGap(31, 31, 31)
                .addComponent(btnMea)
                .addContainerGap(329, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel2);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageNetworkActionPerformed
        // TODO add your handling code here:
    ManageNetworkJPanel manageNetworkJPanel = new ManageNetworkJPanel(system, this);
        jSplitPane1.setRightComponent(manageNetworkJPanel);
        jSplitPane1.setDividerLocation(150);
        jSplitPane1.revalidate();
    }//GEN-LAST:event_btnManageNetworkActionPerformed

    private void btnManageEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEnterpriseActionPerformed
        // TODO add your handling code here:
        ManageEnterpriseJPanel manageEnterpriseJPanel = new ManageEnterpriseJPanel(system, this);
        jSplitPane1.setRightComponent(manageEnterpriseJPanel);
        jSplitPane1.setDividerLocation(150);
        jSplitPane1.revalidate();
     
    }//GEN-LAST:event_btnManageEnterpriseActionPerformed

    private void btnMeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMeaActionPerformed
        // TODO add your handling code here:
         ManageEnterpriseAdminJPanel manageEnterpriseAdminJPanel = new ManageEnterpriseAdminJPanel(system, this);
        jSplitPane1.setRightComponent(manageEnterpriseAdminJPanel);
        jSplitPane1.setDividerLocation(150);
        jSplitPane1.revalidate();
    }//GEN-LAST:event_btnMeaActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
       // 1. 确认是否要登出
    int choice = JOptionPane.showConfirmDialog(this, 
        "Are you sure you want to logout?", 
        "Confirm Logout", 
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE);
    
    if (choice == JOptionPane.YES_OPTION) {
        // 2. 找到最顶层的 MainJFrame 并调用其 triggerLogout 方法
        java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);
        
        if (window instanceof MainJFrame) {
            MainJFrame mainFrame = (MainJFrame) window;
            mainFrame.triggerLogout(); // 调用 MainJFrame 中已有的登出方法
        }
    }
        
    }//GEN-LAST:event_btnLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageEnterprise;
    private javax.swing.JButton btnManageNetwork;
    private javax.swing.JButton btnMea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTree jTree1;
    // End of variables declaration//GEN-END:variables

    void populateTree() {
     // 1. 获取 JTree 的模型
    DefaultTreeModel model = (DefaultTreeModel) jTree1.getModel();

    // ⭐ 关键修正：总是创建一个全新的根节点 ("PetCareSystem")，
    // 并使用 model.setRoot() 方法，强制模型从新根开始构建，彻底消除重复显示。
    DefaultMutableTreeNode root = new DefaultMutableTreeNode("PetCareSystem");
    model.setRoot(root); 
    
    // 注意：不再需要 root.removeAllChildren()，因为 model.setRoot(root) 已经完成了重置。

    // 2. 遍历所有 Network 
    if (system.getNetworkList() != null) {
        for (Network network : system.getNetworkList()) {
            // 使用 Network 对象作为节点的用户对象 (JTree 会显示其 toString() 返回的文本，例如 "Portland")
            DefaultMutableTreeNode networkNode = new DefaultMutableTreeNode(network);
            root.add(networkNode);

            // 3. 遍历 Network 下的所有 Enterprise
            if (network.getEnterpriseDirectory() != null) {
                for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                    DefaultMutableTreeNode enterpriseNode = new DefaultMutableTreeNode(enterprise);
                    networkNode.add(enterpriseNode);
                    
                    // 如果需要显示 Organization，可以在这里继续添加循环
                }
            }
        }
    }

    // 4. 刷新树视图
    model.reload(root); // 重新加载模型，从新的根节点开始
    
    // 5. 展开所有节点，使结构可见
    for (int i = 0; i < jTree1.getRowCount(); i++) {
        jTree1.expandRow(i);
    }
        
    }

    private void loadManageAdminPanel() {
        try {
        // 创建目标面板实例
        ManageEnterpriseAdminJPanel manageEnterpriseAdminJPanel = new ManageEnterpriseAdminJPanel(system, this);
        
        // 关键：清除初始的按钮/布局，加载新面板
        jPanel2.removeAll(); 
        
        // 将面板添加到容器 jPanel2 中
        jPanel2.add("manageEnterpriseAdminJPanel", manageEnterpriseAdminJPanel);
        
        // 显示新添加的面板
        CardLayout layout = (CardLayout)jPanel2.getLayout();
        layout.show(jPanel2, "manageEnterpriseAdminJPanel");
        
        jPanel2.revalidate();
        jPanel2.repaint();
        
    } catch (Exception ex) {
        // ⭐ 捕获异常，并显示错误信息。这有助于找到真正的失败原因。
        JOptionPane.showMessageDialog(this, "加载管理面板失败: " + ex.getMessage(), "内部错误", JOptionPane.ERROR_MESSAGE);
        ex.printStackTrace(); // 将堆栈跟踪打印到控制台
    }
    }

    void restoreDefaultView() {
        // 1. 恢复 jSplitPane1 的右侧组件为包含按钮的 jPanel2
    jSplitPane1.setRightComponent(jPanel2); 
    
    // 2. 可选：重设分割线位置，让 JTree 区域保持一致
    jSplitPane1.setDividerLocation(150); 
    
    // 3. 刷新容器以显示恢复后的视图
    jSplitPane1.revalidate();
    jSplitPane1.repaint(); 
    
    // ⭐ 确保重新加载 JTree，以便在创建新企业后显示新节点
    populateTree();
    }
        
}
